- themes/default/BoardIndex.template.php
User hidden count was wrongly replaced by spider count. This is to fix
that.
Signed-off-by: ahrasis <ahrasis@gmail.com>
> Fix User Hidden Count

- themes/default/index.template.php
When deployed to a SSL server, the stock Elkarte theme causes security warnings due to its insecure link to the html5shim. It should use a scheme-relative URL.
My personal preference would be to avoid linking to a googlecode resource, but this change at least addresses the security issue.
> html5shim should use a scheme-relative URL

- sources/subs/Mail.subs.php
Signed-off-by: emanuele <emanuele45@gmail.com>
> Avoid double Mime-Version in SMTP email headers - fixes #1986

- sources/controllers/Emailpost.controller.php
- sources/subs/EmailParse.class.php
- themes/default/languages/english/Maillist.english.php
Post-By-Email address detects DSN (bounces), records in failed PBE table with a new, bounce-specific failure case. (Previous req Closed to fix a stupid bug)
> Auto bounce detection - Preliminary

- sources/subs/Mail.subs.php
webserver user@host for envelope sender instead of the address
defined in the maillist settings/webmaster adderss. Envelope should
now match the From: address, so DSNs and replies from e.g. gmail
are properly addressed.
The issue did not appear to exist when configured to connect to an
SMTP server.
> Envelope fix

- sources/admin/ManageMaillist.controller.php
- sources/controllers/Emailpost.controller.php
- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
- themes/default/ProfileOptions.template.php
- themes/default/languages/english/Maillist.english.php
- themes/default/languages/english/Profile.english.php
Fixes the rebasing issues in #2027 
@Targren Hope you don't mind if I took the liberty of cleaning up the pull request removing all the unrelated commits. ;D
(Take 3)
Implemented new "Never" option for notifications (Magic Number 99)
Implemented code to automatically change notification_regularity to 99
on receipt of a DSN, with options to control the feature.
Outstanding needs:
Non-standard DSNs/bounces detection is still a stub
Member is not yet notified when emails are enabled
> Auto bounce detection

- sources/Errors.class.php
- sources/QueryString.php
- sources/Request.php
The main thing here is moving the cleanRequest() functions that were in QueryString in to the Request class that we have, so now its with parseRequest().   
There are also a few changes just to separate out some methods, use class values,  and switch some die statements over to error::fatal_error() calls instead.
Any idea why that one is not named Request.class.php and is just Request.php
> Move cleanRequest to be with the rest of Request.

- sources/Hooks.class.php
- sources/admin/Admin.controller.php
- sources/admin/CoreFeatures.controller.php
- sources/admin/ManageAttachments.controller.php
- sources/admin/ManageSearch.controller.php
- sources/admin/PackageServers.controller.php
- sources/admin/Packages.controller.php
- sources/controllers/Xml.controller.php
- sources/subs/AddonSettings.subs.php
- sources/subs/Cache.subs.php
- sources/subs/CacheMethod/Filebased.php
- sources/subs/ManageAttachments.subs.php
- sources/subs/Package.subs.php
- sources/subs/PaidSubscriptions.subs.php
- sources/subs/ScheduledTask.class.php
- sources/subs/ScheduledTask/RemoveTempAttachments.php
Move from scandir, opendir, glob, readdir bla bla etc to SPL objects.  Wrapped all in try/catch although the catch in most cases is a todo for maybe logging.
> Move most directory read functions to SPL

- install/install_1-0_mysql.sql
- install/install_1-0_postgresql.sql
- install/upgrade_elk_1-0_mysql.sql
- install/upgrade_elk_1-0_postgresql.sql
- sources/admin/PackageServers.controller.php
- sources/subs/Package.subs.php
- themes/default/PackageServers.template.php
- themes/default/css/admin.css
- themes/default/css/index.css
- themes/default/languages/english/Packages.english.php
First steps on fixing #1876
The yaml front matter on the addon site should have a new tag added to them for best support, otherwise it may not correctly identify a package as installed from this interface.
`pkid: "same as the package id in the xml file`
which is generall along the lines of
`pkid: "Author:XYZ"`
> Package server updates

- sources/controllers/Memberlist.controller.php
- sources/controllers/Post.controller.php
Removed the preview call, added a JS scroll to the top of the error box, really the category header, so its in yer face.
I did not clean up all those return $this->action_post(); which should not have the return on them, more for 1.1 unless they were done already.
> fix #2077 no preview, scroll error box to top, on post2 error

- install/patch_1-0-4/package-info.xml
Post-release fix, I would avoid call it 1.0.5 or repeat the 1.0.4 release as "b" just for that, I guess bring it to 1.0.5 is good enough. :innocent:
> Fixed package id of the 1.0.4 patch

- sources/controllers/Display.controller.php
Moved the lines to check if the user started the topic above the topicinfo event trigger to prevent an undefined index error in the Polls module when calling upon the topic starter flag.
> Fixes #2146 - Moved block for check if user started topic

- sources/Subs.php
- sources/controllers/PersonalMessage.controller.php
- sources/controllers/Post.controller.php
- sources/ext/bad-behavior/badbehavior-plugin.php
- sources/subs/Drafts.subs.php
- sources/subs/PersonalMessage.subs.php
- sources/subs/Post.subs.php
Some potentially controversial :bomb: things here so proceed with caution :skull: 
1) https://github.com/elkarte/Elkarte/commit/b0f48e8928d7acea7a352ef6defc3db8b4a9e104 Fix and depreciate the permute function.  It was not returning the correct N! results, now it does but it can be dangerous to addon authors and sites in general.
2) https://github.com/elkarte/Elkarte/commit/2363cab836b490645ebec41c13d0b140b5b71dfa Add a  new permute function to allow returning of sets in place of the old function which had to compute a complete solution before returning which for sets > 3 would start to consume memory very quickly.  
This new function should be speed transparent for 99+% of real world usage,  but it will allow a larger parameter list without memory exhaustion unlike the original.  It has …
> For Review

- sources/subs/Likes.subs.php
- sources/subs/Messages.subs.php
- sources/subs/Topic.subs.php
When removing a post, the likes given / received counts were not updated.  
Please look at the proposed fix in like subs.  I did it more as a maintenance function, as its recounts the values, vs an update like_xxxx '-' style.   
There are a couple of complications so I'm really not sure this is the best approach, but you need to reduce the likes given for all members that liked a post that is being deleted.  You then need to reduce the likes received of the post originator by the number of likes the message had received.  To do that given an array of messages id's required a few query's, of course they only happen on delete. 
So message id -> who liked it and who posted it.  Count likes given for them and reduce by one and save.  For the poster, get the number of likes a post received and …
> Like counts were not updated correctly

- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Some minor attempts at trying to resolve the current css mess. : )
> Moving color css to _light and non-color css out of it. 

- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
Still running into issues with getting notifications to function, so all attempts to send disable notifications failing to show results are indeterminate. In the process, discovered another variant DSN (final-recipient instead of original-recipient header), and modified the DSN parser to provide either, if available.
> Mail bounce notify - Prep

- sources/Action.controller.php
- sources/admin/AdminLog.controller.php
- sources/admin/BBC.controller.php
- sources/admin/ManageCalendarModule.controller.php
- sources/admin/ManageMembers.controller.php
- sources/admin/ManageNews.controller.php
- sources/admin/ManagePermissions.controller.php
- sources/admin/ManageSearch.controller.php
- sources/admin/ManageSecurity.controller.php
- sources/admin/ManageServer.controller.php
- sources/admin/ManageSmileys.controller.php
- sources/admin/PackageServers.controller.php
- sources/controllers/Emailuser.controller.php
- sources/controllers/Groups.controller.php
- sources/controllers/News.controller.php
- sources/controllers/OpenID.controller.php
- sources/controllers/PersonalMessage.controller.php
- sources/controllers/Register.controller.php
- sources/controllers/Suggest.controller.php
- sources/controllers/Xml.controller.php
- sources/ext/markdown/markdown.php
- sources/ext/simple_html_dom.php
- sources/subs/DataValidator.class.php
- sources/subs/HttpReq.class.php
This hopefully fixes all cases of potential ambiguity with "variable variables", where a variable is used to reference a member of another structure or class. A lot of cases were probably clear, with using plain variables. Others, where the key was referenced from an array, would break on PHP 7 if not referenced:
$class->{$array['key']}
> Fix all variable variables for PHP 7

- sources/QueryString.php
This changes the regular expression replace function used by the queryless URLs option, so that it doesn't insert the SID parameter if a cookie is set.
> Only emit session id in query parameters when cookie is not set.

- sources/Subs.php
This fixes a bug which would occur with queryless URL generation, where a session code would be inserted between the page name and the /parameters added later, which no longer handles the SID parameter if a cookie is set.
> Fix adding session ID to redirects if a cookie is still set.

- sources/admin/ManageMaillist.controller.php
This corrects the double heading display of the IMAP server. Final result is one heading followed by an information box. 
Relevant post at http://www.elkarte.net/community/index.php?topic=3324.0
> Maillist IMAP heading to info box

- sources/admin/PackageServers.controller.php
- themes/default/PackageServers.template.php
- themes/default/css/admin.css
- themes/default/languages/english/Packages.english.php
This adds / fixes the detection for installed and downloaded packages.  When it comes to bringing this into 1.0.7 I feel we can just replace the PackageServers.controller.php and PackageServers.template.php since the odds of them being modified from the default are near null
> Update package server code 

- themes/default/MessageIndex.template.php
- themes/default/css/index.css
- themes/default/css/rtl.css
Discussed on the site .. http://www.elkarte.net/community/index.php?topic=3358
Not sure we want to fix this for 1.0.7 but here it is anyway
Board name with no natural break points, losses alignment on board index and overflowed the select drop down.  This will partially fix the issue should it ever arise in the real world (the select pull down can still misbehave)
> Updates for very long board names breaking layout

- sources/Subs.php
- sources/subs/BBC/BBCParser.class.php
Alternatively you fix it with something like `$replacechars = array('&sbquo;', '&bdquo;', //etc.` but that'd be a meaningless exercise in futility.
> Drop harmful sanitizeMSCutPaste() function

- sources/Subs.php
- sources/controllers/Emailpost.controller.php
- sources/subs/BBC/Autolink.class.php
- sources/subs/BBC/BBCParser.class.php
- sources/subs/BBC/ParserWrapper.php
- sources/subs/BBC/SmileyParser.class.php
- sources/subs/Profile.subs.php
@joshuaadickerson FYI something related to the parser ;)
Anyway, the way smiley are parsed (i.e. splitting on "\r" and parsing only every even index of the resulting array) looks quite fragile to me (I know it dates back to SMF, but in the next round of refactoring we should do something about it... of course IMO :stuck_out_tongue: ).
> Some fixes for the smiley parser

- sources/subs/UnTgz.class.php
This does not change the returned datatype..
Fixes #2591
> Remove double negative

- sources/subs/Subscriptions-PayPal.class.php
Question: Keep using the `www` endpoint or switch to the recommended `ipnpb`?
> Use SSL when sending postback to PayPal

- sources/SiteDispatcher.class.php
- sources/admin/ManageFeatures.controller.php
This removes integrate_action_frontpage since I think it is overkill. This can prevent conflicts with addons that don't understand the system well enough.
> Call the frontpage method directly

- sources/subs/Permission.subs.php
- sources/subs/SettingsForm.class.php
/**
* Configuration variables and values, for this settings form.
*
* @var array
*/
$config_vars = [
['permissions', 'my_var', 'excluded_groups' => [-1]],
];
> More dynamic group exclusion rules for inline permissions

- sources/Load.php
After the do...while loop to get moderators, $row is null before it gets passed to the integrate_loaded_board function.
> Move integrate_loaded_board before row becomes null

- install/CommonCode.php
- install/Db-check-MySQL.php
- install/Db-check-PostgreSQL.php
Fixes #2849
* lack of globals for Db-check-*.php
* added missing require for un_htmlspecialchars()
* fixed function is closure rather than what the function returns with call_user_func
> Fix installer: globals, require, and closure

- sources/Load.php
- sources/admin/ManageLanguages.controller.php
- themes/default/ManageLanguages.template.php
- Wrong adapter was being used from the settings page, its a file with a db option.
- Missing token now that we use parent:save for both areas, it expects admin-ssc now, so add it as a hidden var.  I think you could just add it to the form and drop admin-lang as well.
- Redefine array so it can be parsed properly by file adapter.  IT was not being parsed as associative as it should, due to adapter changes
- Need to define config[2] even when taking a shortcut or fatal error
> Several fatal errors when setting language defaults

- sources/Load.php
- sources/Subs.php
- sources/admin/Packages.controller.php
- the return in package manager returned to obexit with no template info ... so changed that to a redirect pending us redoing that code in 2.0
- error log is getting a no_session_data, Type of error: General, Headers already sent in at line 0  
Seems since the output buffer is enabled before dieGif() that headers_sent is true, even though nothing has been sent.  So if the function returns sent but no file, lets just clear the buffer and send the gif.
- debug class was not called in one area of assets
> Couple of more 

- sources/controllers/ModerationCenter.controller.php
Fixes that you can't visit the moderation center when `$watched_users` is empty.
```
PHP Fatal error: Uncaught exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /home/frans/www/public_html/elkarte-1.1/sources/controllers/ModerationCenter.controller.php:1710
Stack trace:
thrown in /home/frans/www/public_html/elkarte-1.1/sources/controllers/ModerationCenter.controller.php on line 1710
```
> ModerationCenter.controller: check if $watched_users isn't empty

- themes/default/GenericMessages.template.php
The href value is already there in the array and it makes it easier for a mod to change where the name and avatar link to
> Change profile link to use href from memberContext

- SSI.php
- sources/Load.php
- sources/Request.php
- sources/Subs.php
- sources/admin/ManageAttachments.controller.php
- sources/admin/PackageServers.controller.php
- sources/controllers/Auth.controller.php
- sources/controllers/Register.controller.php
- sources/controllers/Reminder.controller.php
- sources/database/DbTable-mysql.php
- sources/subs/Attachments.subs.php
- sources/subs/Html2Md.class.php
- sources/subs/Package.subs.php
- sources/subs/Util.class.php
- themes/default/Admin.template.php
- themes/default/Display.template.php
- themes/default/GenericControls.template.php
- themes/default/css/admin.css
- themes/default/css/index.css
- themes/default/scripts/dropAttachments.js
- themes/default/scripts/jquery.sceditor.elkarte.js
- themes/default/scripts/script_elk.js
As discussed on the site, there are combo's of *nix distros and their associated lib-xml versions that were not properly working with multi byte words. This should fix that and work with various other issues that can occur.
I'd recommend just replacing the current Html2Md.class.php with this one vs patching it in 1.0.10
Tried to catch up on the version number in the headers as well
> Markdown, headers, misc for 1.0.10

- themes/default/css/index.css
- themes/default/scripts/topic.js
I'm not sure this is what we want to do ... its easy enough to set up some css to clip that
```
width: 18em;
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
padding: 0 .25em;
```
But then when you expand it the "under tab" box containing the name and details will not expand with the image, it will stay at 18em;  
Not sure thats a problem just pointing it out.  In order to have the same behavior I also updated the JS to add a second class name to the name and detail spans so on click they expand out with the image.  Could have done this with a bit less JS, however that would require changing the template and then it would not work with existing themes.
So .... what to do what to do
> ! fix #2895

- themes/default/scripts/elk_jquery_embed.js
I assume the last regex is really only meant for links like these:
```
http://youtu.be/lLOE3fBZcUU?t=1m37s
http://youtu.be/lLOE3fBZcUU?t=97
```
However, it'll incorrectly also match (currently unsupported) playlists:
```
https://www.youtube.com/playlist?list=PL-72lYkqnSfXj7LaTlGfsLhYoNO2xjKkc
```
See http://www.elkarte.net/community/index.php?topic=4435
> Auto-embed: don't match any random string of characters

- tests/travis-ci/setup-results.sh
- tests/travis-ci/setup-script.sh
- tests/travis-ci/setup-server.sh
Don't create test coverage (or run xdebug) when we are not going to use the coverage results.  Only run the coverage when the PR is made.  This prevents creating the coverage reports when making commits to your own branch (should you have any travis running on that)
> Speed up some tests

- themes/default/languages/english/index.english.php
"Powered by" and "Credits" looks very bad with their first letter in lowercase.
> Small language change

- themes/default/css/_besocial/rtl_besocial.css
It's no longer relevant. But if and when it is, unprefixed should always go last.
> [fix] rtl_besocial.css: get rid of outdated -webkit-transform property

- themes/default/Display.template.php
- themes/default/Post.template.php
- themes/default/Register.template.php
- themes/default/VerificationControls.template.php
- themes/default/index.template.php
Some cosmetic changes
- Aria-role menuitem was uselessly noisy. Instead made sure it got labelled in a way that mobile screenreaders can use.
- Return focus to verification box after the user selects 'listen to'. Got props for. 
- Swapped legacy object code out for the audio tag in non-IE browsers. This fixes some, but not all issues with iOS Safari. Further work is needed.
- Some basic attempts to help make likes and polls stand out a bit. May need a larger test group than my current trio.
There were a number of other attempts at fixes, but they did jack so are not included.
> Assorted critical accessibility fixes

- SSI.php
- bootstrap.php
- email_imap_cron.php
- emailpost.php
- emailtopic.php
- index.php
- subscriptions.php
There was *a lot* of duplicate code between index.php and bootstrap ... this is a *first* pass at using a single bootup class for both SSI and "normal" elk to remove the duplication.
This may be a bit much for 1,1.1 ... if so we need to still make a couple of minor changes to allow SSI to load from inside ELK ... so things like portals work 😸 
If we want to go this way i'll add in some quick docblocks, right now this was really a quick and dirty setup so things should work in 1.1.1 and we can do some proper things in 2.0.  Also if so PLEASE test this out, I have not checked the logs (site or server) for issues just yet. 
If however we feel this is to much, I need to make a commit to fix the SSI loading form inside ELK, so let me know which way we feel is the right way (for 1.1.1 that is)
> Use Bootstrap in index.php

- sources/subs/PersonalMessage.subs.php
if the message has no label attahed, $message_labels was never set
> $message_labels needs to be iniitialized per pm

- sources/subs/Html2Md.class.php
- sources/subs/Members.subs.php
- tests/sources/subs/HTML2Md.class.Basic.php
This will now run registration emails through html2md (it did not previous) and updated html2md to also handle plain text links.  Plain links will be wrapped in MD syntax and moved to their own line of text.  Proper line wrapping length will be set to avoid links wrapping.
Old
```
Thank you for registering at Elkarte 1.1 Test. Your username is bla. If you forget your password, you can reset it by visiting http://192.168.10.200/index.php?action=reminder
Before you can login, you first need to activate your account. To do so, please follow this link:
http://192.168.10.200/index.php?action=register;sa=activate;u=509;code=6Wf8AYpRH99O80
Should you have any problems with activation, please visit http://192.168.10.200/index.php?action=register;sa=activate;u=509 use the code "6Wf8AYpRH99O80". …
```
> Address #3238

- sources/Load.php
- sources/subs/DataValidator.class.php
- sources/subs/HttpReq.class.php
- sources/subs/Ila.integrate.php
- themes/default/ManageSmileys.template.php
I don't see any changes to these files since 1.1.5, so this reverts the headers back.  Am I missing a change somewhere?
> I don't think there files actually changed ?

- sources/controllers/Unread.controller.php
- sources/subs/Topic.subs.php
- sources/subs/Unread.class.php
Fixes #3341
Most topic index (board view) queries were already appropriately optimized.
The PM queries are still a mess, but less critical (guests don't stumble into a 100k pm chain), and best addressed with personal conversations in 2.0.
Per #3230 I also removed the temporary table creation from unread replies.
> Replaced queries in Topic.subs.php and removed temp table creation from unread.

- sources/SiteDispatcher.class.php
- sources/admin/ManageFeatures.controller.php
- sources/controllers/Likes.controller.php
- sources/controllers/Members.controller.php
- sources/controllers/Notify.controller.php
- sources/subs/ManageFeatures.subs.php
- sources/subs/Members.subs.php
- sources/subs/MentionType/LikemsgMention.php
- sources/subs/MentionType/MailfailMention.php
- sources/subs/MentionType/MentionMessageAbstract.php
- sources/subs/MentionType/MentionTypeInterface.php
- sources/subs/MentionType/MentionmemMention.php
- sources/subs/MentionType/QuotedmemMention.php
- sources/subs/MentionType/RlikemsgMention.php
- sources/subs/Notification.subs.php
- sources/subs/NotificationsTask.class.php
- sources/subs/ProfileOptions.subs.php
- themes/default/Notify.template.php
- themes/default/languages/english/EmailTemplates.english.php
- themes/default/languages/english/MaillistTemplates.english.php
- themes/default/languages/english/index.english.php
This extends  the current unsubscribe links from topics/boards to all our various mentions (quoted, liked, mentioned, etc) to allow easy unsubscribe.  It also adds additional information to those mentions, namely the subject in which the event occurred, thats a bit nicer for the email.
Adds the static frequency value to the mention controllers, currently all frequencies were shown for all methods but that was not really correct (e.g. bounced is only notify not email).  With this the method allowed frequencies is shown in the ACP.
links are all now a one button affair with some protections to avoid spamming and general mischief.  I'm not super happy with some things but in general the token is a blowfish crypt with user and extra site salt, this makes a brute force a time consuming process …
> Unsubscribe improvements

- install/Install_Controller.php
- install/upgrade.php
- sources/Load.php
- sources/controllers/Auth.controller.php
- sources/controllers/OpenID.controller.php
- sources/controllers/ProfileOptions.controller.php
- sources/subs/Members.subs.php
- sources/subs/Profile.subs.php
Had to close and redo this one as a wrong commit was in this original PR (one from another PR) and in fixing that things went bad quickly!
This fixes a couple of minor bugs with setting incorrect cookies when a password is changed. Introduced probably back in 1.0 😭
This also increases the salt length from 4 ~~to 8~~ to 16 which provides a vast increase in probable values. It ~~does not~~ does force it to happen but should not cause a logout but instead update the salt and cookie on the fly.  It will use it for new members and do updates on existing members during logout and password changes.
In 2.0 all of this cookie code should be centralized in a class, for setting/getting/clearing
> Some more milk with the cookies

- sources/admin/ManageThemes.controller.php
- sources/subs/Admin.subs.php
When the forum files are read-only:
1. The `index.php?action=admin;area=maintain;sa=routine;activity=version` command crashes because the `$tmp_version_info` variable is not set in the `getFileVersions` function in Admin.subs.
2. A custom theme folder cannot be installed because the ManageThemes controller incorrectly looks for `query` parameters when identifying the `$method = 'path'` mechanism. The submission is actually in a `post` request.
This request solves these two problems.
> Fixes for read-only source files

- .travis.yml
- Settings.sample.php
- sources/BrowserDetector.class.php
- sources/Load.php
- sources/admin/ManageAttachments.controller.php
- sources/admin/ManageMaillist.controller.php
- sources/controllers/Emailpost.controller.php
- sources/controllers/ProfileInfo.controller.php
- sources/controllers/Spellcheck.controller.php
- sources/controllers/Xml.controller.php
- sources/subs/Attachments.subs.php
- sources/subs/BBC/BBCParser.php
- sources/subs/BBC/Codes.php
- sources/subs/Drafts.subs.php
- sources/subs/EmailFormat.class.php
- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
- sources/subs/Graphics.subs.php
- sources/subs/Html2BBC.class.php
- sources/subs/Html2Md.class.php
- sources/subs/Mail.subs.php
- sources/subs/Notification.subs.php
- sources/subs/RepairBoards.subs.php
- sources/subs/Unread.class.php
- sources/subs/VerificationControls.class.php
- tests/sources/subs/HTML2Md.class.Basic.php
- tests/travis-ci/setup-server.sh
- themes/default/Maillist.template.php
- themes/default/css/index.css
This fixes any 7.4 errors that I have encountered, could be more but this is a start.  Some of the 7.4 issues were in fact minor real errors so those were fixed as well
Noticed a bug in the re-encode image function when using imagik, it was not stripping the exif headers and that is where mischievous code could exist, so it was 100% ineffective.
Fixed a few errors reported on the site or in the issues log
Made updates to PBE based on reported errors as well as things found while giving it a good thrashing.   There were some new email content types to deal with and the plain text email link issues.  That fix was a bit eh? but it does what is needed.
Make updates to the build environment which was failing (mostly due to xcache) but also reduced the number of environments.  I'm not sure what …
> PHP 7.4 updates and "other"

- bootstrap.php
- install/TemplateUpgrade.php
- install/upgrade.php
- themes/default/css/install.css
- themes/default/languages/english/Install.english.php
Just a bit more work on this ... 
Now after install, if you don't delete the install directory as part of the installer, or it fails, you will still be redirected to upgrade.  But it now passes the installed forum version so upgrade knows its can't upgrade to what it already is.  
Instead it jumps to the end of upgrade and informs that you must delete the install directory.  I could have provided the checkbox to attempt this but decided not to for several reasons.  
This is better than what is there now, pic attached of where to get sent to as well.
> Address more of #3225

- SSI.php
Fixes: 
Type of error: database
Database Error: ERROR: column "lmr.id_msg" must appear in the GROUP BY clause or be used in an aggregate function
File: /var/www/html/PGElkarte/SSI.php
Line: 511
> Fix GROUP BY issue on pgsql

- sources/ElkArte/Database/Mysqli/Dump.php
- sources/ElkArte/Database/Postgresql/Dump.php
- sources/ElkArte/Database/Postgresql/Query.php
- sources/ElkArte/Errors/Log.php
- sources/ElkArte/Recent.php
- sources/ElkArte/ScheduledTasks/Tasks/UserAccessMentions.php
- sources/ElkArte/Search/API/Sphinxql.php
- sources/ElkArte/Search/API/Standard.php
- sources/ElkArte/Unread.php
- sources/subs/BadBehavior.subs.php
- sources/subs/Bans.subs.php
- sources/subs/Calendar.subs.php
- sources/subs/Likes.subs.php
- sources/subs/Maillist.subs.php
- sources/subs/ManageAttachments.subs.php
- sources/subs/Membergroups.subs.php
- sources/subs/Members.subs.php
- sources/subs/Mentions.subs.php
- sources/subs/MessageIndex.subs.php
- sources/subs/Messages.subs.php
- sources/subs/Moderation.subs.php
- sources/subs/Modlog.subs.php
- sources/subs/PaidSubscriptions.subs.php
- sources/subs/PersonalMessage.subs.php
- sources/subs/Profile.subs.php
- sources/subs/ProfileHistory.subs.php
- sources/subs/ScheduledTasks.subs.php
- sources/subs/SearchEngines.subs.php
- sources/subs/Smileys.subs.php
- sources/subs/Topic.subs.php
All the db's that we support use that syntax, so this make the core postgre/mysql/mariadb compliant.  I left the postgre translation in place for addons usage but perhaps we should remove that ?
> Update querys from MySQL unique LIMIT offset, start to more universal LIMIT start OFFSET offset

- .github/setup-failure.sh
- .github/setup-selenium.sh
- .github/workflows/tests.yaml
- sources/ElkArte/AdminController/Admin.php
- sources/ElkArte/AdminController/ManageMembers.php
- sources/ElkArte/AdminController/ManageRegistration.php
- tests/install/ElkArteInstallWeb.php
- tests/sources/controllers/AttachmentTest.php
- tests/sources/controllers/AuthWeb.php
- tests/sources/controllers/ElkArteWebSupport.php
- tests/sources/controllers/EmailUserTest.php
- tests/sources/controllers/PostTest.php
- tests/sources/controllers/RegisterWeb.php
- tests/sources/controllers/acpAddGroupWeb.php
- tests/sources/controllers/acpManageMembersWeb.php
This updates the webtests to use chromedriver in place of htmldriver.  htmldriver would pass or fail at random (really due to test errors) and in the latest selenium driver (the pi version) it was removed from the base so you have to install a separate webdriver.  This update helps for that future set of constraints plus hopefully more consistent runs and error output.
I tried to use geckodriver but after many attempts could not get it to run.  It took a while to get chromedriver to work as well due to some w3c errors.
I tried to use selenium as a GHA service but phpunit selenium would not connect to that docker container.  Could not figure that out so went back to running it on the local
Found a couple of legit errors in the code and patched those.  Found legit errors in the test and …
> Chromedriver

- sources/ElkArte/Themes/ThemeLoader.php
- tests/sources/controllers/AuthWeb.php
- tests/sources/controllers/ElkArteWebSupport.php
- tests/sources/controllers/PostTestWeb.php
- tests/sources/controllers/ProfileForumWeb.php
- tests/sources/controllers/ProfileInfoWeb.php
- tests/sources/controllers/RegisterWeb.php
- tests/sources/controllers/acpAddGroupWeb.php
- tests/sources/controllers/acpManageMembersWeb.php
- tests/sources/subs/Boards.subs.Test.php
@emanuele45 This one is a bit odd so not sure this is the fix: https://github.com/elkarte/Elkarte/pull/3455/commits/946699e296499bbb3f7b123cd413f73f886901e0
The RegisterWeb tests were failing every time (yes they still fail on occasion, its the pain of headless web testing).  Anyway at first I thought it was a testcase issue but was able to repo on my test site once.  
The general flow is user.php ```load()``` is called ... this will call ```loadUserById()``` which will then call ```compileInfo()``` 
The ```compileInfo()``` function will call ```'language' => $this->getLanguage(),``` which will fail if ```user::info``` has not been loaded by some path.  Now ```user::info``` is loaded as part of the ```compileInfo()```function but that is after that ```'language' => …
```
> Fix broken test due to not calling parent setup

- sources/database/Db-mysql.class.php
- sources/database/Db-postgresql.class.php
- sources/database/Db.php
It doesn't have any impact or effect when '' is used, as that evaluates to INSERT on the line starting $queryTitle
> Removed initial default argument on insert

- sources/controllers/Notify.controller.php
- sources/subs/Emailpost.subs.php
- sources/subs/Html2Md.class.php
- sources/subs/Mail.subs.php
- sources/subs/Package.subs.php
- tests/sources/subs/Curl_Fetch_Webdata.class.Test.php
- tests/sources/subs/HTML2Md.class.Basic.php
- themes/default/ManageMembergroups.template.php
- The current static array does not allow addons to supply their own unsubscribe method, this fixes that.
- ILA links in PBE were being double wrapped
- PBE code was being inserted in db and messages where it should not be (e.g. registration).  Harmless until you try to do an 1.0 to 1.1 upgrade since the db codes would be no conforming and the table update failed
- additional adjustments to pbe line length and base64 encoding codes
- the depreciated notice will really not be fixed here, ```octdec``` is likely getting a dec from the filesys and that makes it toss the error (or any whitespace as well which this does address)
> Latest collection of 1.1.7 updates

- sources/subs/Html2Md.class.php
- tests/sources/subs/HTML2Md.class.Basic.php
In a previous PR I fixed some nagging line length issues (well lets be honest, its just only a bit better) However that fix forced things through the wrapping function which in review eats empty ```\n``` lines.  
So this update address that functional error and what were likely a couple of "fixes" to work around that behavior, one with nested lists and one with too few line ends compared to the supplied makrup.
Could there be more bumps in here? Why yes, yes there could.
> some more html to md "fixes"

- sources/subs/Html2Md.class.php
The protection of xml tags so dom parser does not fail, can also silently hide html tags that should be converted to MD
This just fixes the annoying one where you end a sentence with?
So just like above that now trailing ```<br />```, complements of the BBC parser, is hidden during the html->md conversion and then its restored at the end, resulting in``` ?<br />``` being created in the MD output.  This PR fixes the "br" single case.  There have to be others as well, but thats for 2.0
> An oldie but a goodie

- sources/database/Db-postgresql.class.php
Changes to make 1.1.8 compatible with PHP 8.1 
@Spuds @emanuele45 there will be other changes needed strftime/gm_strftime is another error, do you want those in a different PR or is this one ok?
> Updated Db-PostgreSQL to be PHP 8.1 compatible

- sources/controllers/Display.controller.php
- sources/controllers/Recent.controller.php
- themes/default/Display.template.php
- themes/default/css/index.css
- themes/default/scripts/like_posts.js
Changed like_button to react_button, likes_button to reacts_button, so that AdBlockPlus doesn't remove the likes button when Social Media Blocking is enabled
Fixes #3564
> AdBlockPlus like_button fix

- sources/subs/Html2Md.class.php
- themes/default/Display.template.php
Also pulled in many processing enhancements from 2.0.  
For anyone having the broken link issue, just replace the 1.1.8 version with this new file.
> Update html2md so it does not break links

- sources/ElkArte/Controller/Markasread.php
- sources/ElkArte/SiteDispatcher.php
- themes/default/scripts/script_elk.js
This is an attempt to redo the mark as read controller which was previous hot wired to work with API calls and other mystery.   
I'm not ecstatic with where it is, but I feel its now workable.  It properly passes though the action controller as a "normal" controller, and handles the API calls through the normal flow and not injected to a random method.  Still lots of redirect exits and return deliciousness to keep everyone guessing.  Better yes, great no, at least its no longer in the action array!
Also fixed the JS since I had not updated that when I changed all the CSS (Note these changes rely on the fix3 commit changes as well, respectably the CSS changes to boardindex, I should have had them in this PR but sometimes that is now how things roll 🎲
> Mark as read controller

- .github/bootstrap.php
- .github/phpunit-mysql.xml
- .github/phpunit-webtest.xml
- .github/setup-elkarte.sh
- .github/setup-results.sh
- .github/setup-selenium.sh
- .github/workflows/tests.yaml
- Settings.sample.php
- Settings_bak.sample.php
- composer.json
- sources/subs/Members.subs.php
- tests/sources/LanguageStringsTest.Basic.php
Some minor improvements to the testbed
- use 20.04
- user phpunit9 for php8 tests (only to allow test coverage)
- update language file locations
- cleanup some composer dependency's
- drop xdebug filer list (its was removed or depreciated in 9.0)
- Can't convert to 9.0 due to selenium test coverage not working on it.  I could do what I did with the php8.0 test but not worth the effort at this time.
> Test updates

- sources/ElkArte/AdminController/ManageThemes.php
- sources/ElkArte/Controller/Auth.php
- sources/ElkArte/Controller/Profile.php
- sources/ElkArte/Controller/ProfileOptions.php
- sources/subs/Themes.subs.php
- themes/default/ManageThemes.template.php
- themes/default/ProfileOptions.template.php
This PR breaks out the user theme pick from the Admin controller (managethemes).
Previously when the user was choosing their theme of choice, from their profile, the code they were running was actually in the Admin conrtoller `ManageThemes.php` which contained various section they were allowed to run as long as they were not the Admin, yes that is how it was LOL  Anyway it was not ideal construct so now its a separate profile function and separate profile templates.   This does cause some amount of duplication but at least things are properly aligned.  
As always there were a few bugs stomped along the way, theme preview was not working, variant selection lists were wrong and always showed the default theme, etc
> Theme pick

- sources/ElkArte/Controller/Display.php
- sources/ElkArte/Modules/Poll/Display.php
- themes/default/Display.template.php
A start, and for now, and end to breaking up `Display.php` into a series of smaller methods.  
I did what I could to move all `$context` manipulation out of the main flow and instead directly use the `topicinfo` values.  The topicinfo values were being used  to set $context values and then use those $context values were used in various logic points, pretty messy.   Now once information are known, or computed, `$context` is loaded for the templates.  Still some rough spots as some subs don't provide return values but instead stuff $context with the result.
As always I'm sure I've caused some issue somewhere as the order of what is computed has changed to some degree, but I think its more readable now and in a place that real refinement can take place.
> Break display controller into a series of methods

- sources/ElkArte/AttachmentsDisplay.php
- sources/ElkArte/BBC/BBCParser.php
- sources/ElkArte/BBC/Codes.php
- sources/ElkArte/Controller/Attachment.php
- sources/ElkArte/IlaIntegrate.php
- sources/ElkArte/Modules/Attachments/Display.php
- sources/subs/Attachments.subs.php
This started as a simple return both a below post attachment array and the ILA array.  
Next was the ILA code was not handling non approved attachments in a graceful way (simply ignored them, left bad attach code in place), this now will present a pending approval image.  Renamed the `action_no_attach` method to `action_text_to_image`, since its used for both attachment missing and awaiting activation string, and added some features.
Next while testing ILA, there were a few edge problems, like if someone used a width attribute on a file attachment, plain `[attach]tags[/attach]` were not working.  detecting the no approved status was problematic, and a several other tag creation issues.  
To fix the problems and not make the ILA code overly complex, and still not working in all cases, I …
> Updates to ILA

- sources/ElkArte/AdminController/ManageEditor.php
- sources/ElkArte/BBC/BBCParser.php
- sources/ElkArte/BBC/MarkdownParser.php
- sources/ElkArte/Languages/Admin/English.php
- sources/ElkArte/Languages/Help/English.php
We can call this experimental as who know what edge cases will show up.  This allows us to use some basic markdown syntax in the editor and have it render.  Added are:
`**Text** or __Text__ => [b]Text[/b]`
`*Text* or _Text_ => [i]Text[/i]`
`~~Text~~ => [s]Text[/s]`
` 'Text' => [icode]Text[/icode]`
` '''Text''' => [code]Text[/code]`
`> Text => [quote]Text[/quote]`
`--- or *** or ___ => [hr]`
The code ones are really backticks `, could not escape it so used single quote ' in the above list.
The major issue with code, inline or fenced, is that it will not be cleaned by preparsebbc, so if its wrong, its wrong.  🤷‍♂️ I suppose it could be added.
> Add basic Markdown support to the message parser

- sources/Subs.php
Check if shell_exec is disabled before attempting to use it to avoid the PHP 8.1 error.
> Check if shell_exec is disabled on functions list

- sources/admin/ManageAttachments.controller.php
- sources/subs/Graphics.subs.php
- themes/default/css/index.css
Some systems may have imagick installed w/o webp support but also have GD w webp support.  This change allows fallback to use GD for processing webp images, the previoud logic was that the imagick install would always have the same capabilities as GD but this is not always the case.
> Fix issue that prevented fallback to GD for webp
