- sources/controllers/Memberlist.controller.php
- sources/subs/Memberlist.subs.php
- themes/default/css/index.css
Since mostly everybody agree with this here:
http://www.elkarte.net/community/index.php?topic=2398.0, this is the PR
to add avatar to memberlist.
Signed-off: Ahmad Rasyid Ismail "ahrasis" ahrasis@gmail.com.
> Add Avatar To Memberlist

- sources/controllers/Emailpost.controller.php
- sources/controllers/Recent.controller.php
- sources/controllers/RemoveTopic.controller.php
- sources/subs/Emailpost.subs.php
- sources/subs/Memberlist.subs.php
- sources/subs/Members.subs.php
- sources/subs/Notification.subs.php
- sources/subs/Profile.subs.php
- sources/subs/Topic.subs.php
- themes/default/Admin.template.php
- themes/default/Display.template.php
- themes/default/languages/english/Who.english.php
- themes/default/languages/english/index.english.php
- themes/default/scripts/script.js
- themes/default/scripts/theme.js
! Type of error: Critical Database error, given array of integer values is empty. (messages) Function: removeTopics
! after restore of single message or topic, return somewhere normal
Now plus some other stuff :angel: 
more :poop:
even more :poop:
> restoring a message resulted in empty message value error

- sources/controllers/Memberlist.controller.php
- sources/controllers/MergeTopics.controller.php
- sources/controllers/Recent.controller.php
- sources/subs/BoardsList.class.php
- sources/subs/Memberlist.subs.php
- themes/default/MergeTopics.template.php
- themes/default/Recent.template.php
- themes/default/css/index.css
- themes/default/index.template.php
- themes/default/languages/english/Editor.english.php
- themes/default/scripts/elk_jquery_plugins.js
I backported here the avatar in member list from @ahrasis
> Another round of smallish fixes and stuff.

- index.php
Also removed a duplicate CACHE_STALE define, and moved start time before the defines (they're slow).
> Minor code cleanup, added fastcgi exit for scheduled tasks.

- sources/CurlFetchWebdata.class.php
- sources/Session.php
- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
- sources/subs/Mail.subs.php
- sources/subs/Messages.subs.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Few more minor annoyances fixed for the 1.03 branch
> Minor updates for 1.03

- Settings.sample.php
- Settings_bak.sample.php
- bootstrap.php
- email_imap_cron.php
- emailpost.php
- index.php
- install/install.php
- install/installcore.php
- install/upgrade.php
Also moved some common constants in the installer to a new file, preferably for common code between the installer and upgrader.
The SITE_SOFTWARE thing may be debatable, but I figured it would be good if you e.g. moved elkarte.net to https.
> Various PHP 5.3 things and code cleanup

- sources/admin/ManageFeatures.controller.php
Signed-off-by: emanuele <emanuele45@gmail.com>
> Make removed likes invisible when toggling the setting to not notify

- sources/Subs.php
add ;api for consistency with ;xml
> Fix parse bbc disabled tag issue

- sources/SiteDispatcher.class.php
- sources/controllers/Suggest.controller.php
- tests/sources/controllers/RegisterWeb.php
Controllers can only be classes and no more functions.
This is a backward-incompatible change, but I guess not many people wrote controllers to begin with, and those that did were using OOP already.
> No more functions as controllers

- SSI.php
- index.php
Signed-off-by: emanuele <emanuele45@gmail.com>
> As reminded by Spuds let's update the CACHE_STALE for the release

- sources/controllers/Memberlist.controller.php
- sources/controllers/Recent.controller.php
- sources/subs/Memberlist.subs.php
- themes/default/Memberlist.template.php
- themes/default/css/index.css
Missing the use of the new text string for mark these as read
Improve stabilization  (I think) of the avatars in the member list.  I put this change on the site for review
> Couple of 1.0.3 patch issues

- sources/Subs.php
- sources/admin/Maintenance.controller.php
- sources/admin/ManageAttachments.controller.php
- sources/admin/ManageFeatures.controller.php
- sources/admin/ManageMail.controller.php
- sources/admin/ManageSearch.controller.php
- sources/admin/ManageThemes.controller.php
- sources/admin/PackageServers.controller.php
- sources/admin/Packages.controller.php
- sources/controllers/Post.controller.php
- sources/controllers/ProfileAccount.controller.php
- sources/subs/Mail.subs.php
- sources/subs/Members.subs.php
- sources/subs/Messages.subs.php
- sources/subs/Package.subs.php
- sources/subs/RepairBoards.subs.php
- sources/subs/ScheduledTask.class.php
- sources/subs/ScheduledTask/Birthdayemails.task.php
- sources/subs/ScheduledTasks.subs.php
- sources/subs/Topic.subs.php
Move most occurrences of set_time_limit and apache_reset to a central location so that it does not work in one place instead of not working in many :P
I left the ones that were in the various db backup functions as those were done uniquely.  I think they could be moved, but was not sure.
> Set Time Limit

- sources/Subs.php
- sources/admin/ManageMaillist.controller.php
- sources/admin/ManagePermissions.controller.php
This should be the last of the create functions ...
> ! fix #2013

- sources/Autoloader.class.php
- sources/SiteDispatcher.class.php
- sources/controllers/Xml.controller.php
> Couple of minor things

- sources/Security.php
- sources/admin/ManageMaillist.controller.php
- sources/controllers/News.controller.php
- sources/subs/ScheduledTask.class.php
- broken birthday emails
- pbe "unkonwn" from email repair error
- rss2 feeds were not validating
> Items for 1.0.4

- themes/default/scripts/admin.js
- themes/default/scripts/drafts.js
- themes/default/scripts/drafts.plugin.js
- themes/default/scripts/elk_jquery_plugins.js
- themes/default/scripts/jquery.sceditor.elkarte.js
- themes/default/scripts/post.js
- themes/default/scripts/profile.js
- themes/default/scripts/register.js
- themes/default/scripts/script.js
- themes/default/scripts/script_elk.js
- themes/default/scripts/spellcheck.js
- themes/default/scripts/splittag.plugin.js
- themes/default/scripts/topic.js
Minor updates to the JS,  ... breaking item could be the move away from esacpe and to8bit
- spelling
- docblocks
- resuse of jq selectors
- update some dependencies
- minor code cleanup
- removed cur_session_var = 'sesc'; old theme compatabilty
> JS Updates

- sources/Errors.class.php
The function / file / line debug info was out of sync
> Debug error trace was out of step

- sources/admin/ManageScheduledTasks.controller.php
- sources/subs/Html2Md.class.php
- themes/default/Display.template.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/scripts/jquery.sceditor.elkarte.js
Fix a few open issues on 1.0.3
Also a fix for markdown code blocks that caused an issue during conversion and an improved line wrapper.
> Clear some more 1.0.3 issues from the log

- sources/subs/Graphics.subs.php
per: http://www.elkarte.net/community/index.php?topic=2509.0
has no ACP settings, its simply On should you have imagik support.
> Image Orienatation

- sources/controllers/Memberlist.controller.php
- sources/subs/Memberlist.subs.php
- themes/default/scripts/admin.js
This should fix #2074
Seems to easy, so please take a look :innocent:
> Search select 

- install/generate_detailed-version.php
- install/install.php
- install/upgrade.php
- sources/BrowserDetector.class.php
- sources/Security.php
- sources/admin/ManageMaillist.controller.php
- sources/admin/ManageScheduledTasks.controller.php
- sources/admin/PackageServers.controller.php
- sources/controllers/Mentions.controller.php
- sources/controllers/Post.controller.php
- sources/controllers/RemoveTopic.controller.php
- sources/subs/Graphics.subs.php
- sources/subs/Html2Md.class.php
- sources/subs/Memberlist.subs.php
- sources/subs/Mentions.subs.php
- sources/subs/Package.subs.php
- sources/subs/ScheduledTask.class.php
- themes/default/Display.template.php
- themes/default/GenericControls.template.php
- themes/default/PackageServers.template.php
Darn I was too fast clicking with the other PR. lol
BTW, it's the fix for the bug reported at https://github.com/SimpleMachines/SMF2.1/issues/2896
> Last minute fixelt

- sources/subs/Editor.subs.php
- themes/default/css/index.css
fix #2090 plus small tweak :innocent:
> Last second 1.0.4 tweaks

- sources/Load.php
- sources/Security.php
- sources/Subs.php
- sources/database/Db-abstract.class.php
- sources/database/Db.php
- sources/subs/Admin.subs.php
- sources/subs/Attachments.subs.php
- sources/subs/Auth.subs.php
- sources/subs/Bans.subs.php
- sources/subs/Boards.subs.php
- sources/subs/BoardsList.class.php
- sources/subs/Calendar.subs.php
- sources/subs/Categories.subs.php
- sources/subs/Drafts.subs.php
- sources/subs/Editor.subs.php
- sources/subs/Emailpost.subs.php
- sources/subs/Likes.subs.php
- sources/subs/Mail.subs.php
- sources/subs/Maillist.subs.php
- sources/subs/Maintenance.subs.php
- sources/subs/ManageAttachments.subs.php
- sources/subs/ManageFeatures.subs.php
- sources/subs/ManagePermissions.subs.php
- sources/subs/Membergroups.subs.php
- sources/subs/Members.subs.php
- sources/subs/Mentions.subs.php
Well, the code still merges, so I guess I can just send the PR. :angel: 
I never planned to switch all the queries to this style in a PR, just "encourage" the use in future queries and maybe convert while going on.
> New style queries - fixes #2041

- sources/admin/PackageServers.controller.php
Also serves as a test of my local environment
> $forum_version wasn't initialized

- install/Db-check-PostgreSQL.php
> Fixed postgresql additional file extension

- index.php
> Added checking for fastcgi_finish_request() exists

- themes/default/scripts/elk_jquery_embed.js
Required now that Chrome has removed Flash functionality.
> Fixes #2202 - Updated video embedding to HTML5 and made src links protocol agnostic

- install/install_1-1.php
- sources/controllers/PersonalMessage.controller.php
- sources/modules/Drafts/DraftsPersonalMessageModule.class.php
- sources/modules/Drafts/DraftsPostModule.class.php
- sources/subs/Drafts.subs.php
This is a quick try at distinguish drafts saved by the user and autosaved.
This are the basics: just save. There are several things missing like shiny icons, better cutting and stuff like that.
> Drafts save flag - fixes #2206

- themes/default/Display.template.php
- themes/default/PersonalMessage.template.php
- themes/default/Post.template.php
- themes/default/Recent.template.php
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
continue fixing areas from the div removal
> Few more theme updates

- sources/admin/ManageFeatures.controller.php
- sources/admin/ManageTopics.controller.php
- themes/default/Display.template.php
- themes/default/Maillist.template.php
- themes/default/ManageNews.template.php
- themes/default/ManagePaid.template.php
- themes/default/PersonalMessage.template.php
- themes/default/Post.template.php
- themes/default/Profile.template.php
- themes/default/ProfileInfo.template.php
- themes/default/ProfileOptions.template.php
- themes/default/css/_light/index_light.css
- themes/default/css/admin.css
- themes/default/css/index.css
- themes/default/languages/english/Admin.english.php
- themes/default/languages/english/ManageSettings.english.php
- themes/default/scripts/admin.js
- themes/default/scripts/post.js
- themes/default/scripts/theme.js
Continuing to clean up after the div removal
Consolidating / combining along the way
> Theme updates

- index.php
- sources/Request.php
- sources/SiteDispatcher.class.php
- sources/Subs.php
- sources/admin/ManageMembers.controller.php
- sources/controllers/Auth.controller.php
- sources/controllers/PersonalMessage.controller.php
- sources/controllers/Register.controller.php
- sources/controllers/Reminder.controller.php
- sources/modules/Verification/VerificationRegisterModule.class.php
- sources/subs/Auth.subs.php
- sources/subs/Members.subs.php
- sources/subs/OpenID.subs.php
- sources/subs/Profile.subs.php
- sources/subs/Sound.subs.php
- sources/subs/VerificationControls.class.php
- tests/sources/SubsTest.php
- themes/default/Login.template.php
- themes/default/Register.template.php
- themes/default/languages/english/Who.english.php
Update the registration controller
Point all actions= that were inside of register to be sa=xxx so they are dispatched by the controller vs the global dispatcher.
Lots of other tweaks in this as well, some refactoring, etc ...  lets see if it merges
> Register controller Updates

- sources/admin/ManageSearch.controller.php
- sources/admin/ManageServer.controller.php
- sources/controllers/PersonalMessage.controller.php
- sources/controllers/Search.controller.php
- sources/modules/Drafts/DraftsPersonalMessageModule.class.php
- sources/subs/CacheMethod/CacheMethodAbstract.php
- sources/subs/Drafts.subs.php
- sources/subs/Search.subs.php
- sources/subs/Search/API/SphinxSearch.class.php
- sources/subs/Search/API/SphinxqlSearch.class.php
Some stuff to fix most of the current blocking issues.
@Spuds can you have a look at ebc46342082554c785b8b7372341079915c41886 and see if it actually fixes the problem? ;D
> Fixes again

- SSI.php
- index.php
- sources/Debug.class.php
- sources/Subs.php
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
My IDE is still going nuts, so I figured I would address the css stuff in small chunks.
Also, setup a symlinked deployment environment. Turns out this does not work well with __DIR__
> Some general style and issue cleanup

- themes/default/css/_besocial/admin_besocial.css
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
Trying to update besocial to work with the damage I caused.
> Getting beSocial up to 1.1 markup

- sources/admin/ManageFeatures.controller.php
- sources/controllers/Display.controller.php
- sources/controllers/Likes.controller.php
- sources/subs/Messages.subs.php
- sources/subs/PersonalMessage.subs.php
- sources/subs/Profile.subs.php
- themes/default/GenericMessages.template.php
- themes/default/ProfileOptions.template.php
- themes/default/languages/english/index.english.php
- themes/default/scripts/profile.js
forgot to update the file headers for v1.0.6 in my last batch
+less greedy check on the signature font size
> Clean up after myself

- SSI.php
This change to the SSI script makes way for changes to Simple Portal, and possibly other scripts, to display the topic starter's name and profile link.
Eventually, I may make further changes to include such info as the timestamp of the opening post. All the other info I need is already provided, though.
> Add original poster block to ssi_recentTopics query

- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Got about 25-30% done, at least for these two files.
> More moving color css to _light and non-color css, part II

- themes/default/css/_light/admin_light.css
- themes/default/css/_light/index_light.css
- themes/default/css/admin.css
- themes/default/css/index.css
Made it through the admin files and more of the core file.
> CSS segregation, Part III

- install/install_1-1.php
- install/upgrade_1-0.php
- sources/controllers/Attachment.controller.php
- sources/controllers/Draft.controller.php
- sources/controllers/Post.controller.php
- sources/modules/Attachments/AttachmentsPostModule.class.php
- sources/modules/Drafts/DraftsPersonalMessageModule.class.php
- sources/modules/Drafts/DraftsPostModule.class.php
- sources/subs/Attachments.subs.php
- sources/subs/BBC/Codes.class.php
- sources/subs/Drafts.subs.php
- sources/subs/Ila.integrate.php
- sources/subs/InLineAttachment.class.php
- themes/default/Post.template.php
- themes/default/languages/english/Post.english.php
- themes/default/scripts/drafts.js
- themes/default/scripts/drafts.plugin.js
- themes/default/scripts/dropAttachments.js
- themes/default/scripts/post.js
- themes/default/scripts/script_elk.js
It mostly works, I think.
It may be good enough for a beta even though it's broken (there is (still) a race condition for sure).
> A bunch of stuff for ILA and drafts

- sources/Load.php
- sources/admin/ManagePermissions.controller.php
- sources/controllers/Auth.controller.php
- sources/controllers/ProfileAccount.controller.php
- sources/ext/bad-behavior/badbehavior-plugin.php
- sources/subs/EmailFormat.class.php
- sources/subs/Graphics.subs.php
- sources/subs/Html2BBC.class.php
- sources/subs/Html2Md.class.php
- sources/subs/Mail.subs.php
- sources/subs/Members.subs.php
created branch 1.0.7 for these, if that does not happen, should be ported over to 1.1
the changes to Html2Md.class look worse then they are (broke down two methods that had gotten long), the intention during upgrade would be to replace the file with the new one.
> Fix a few of the open issues

- themes/default/css/_light/index_light.css
- themes/default/css/index.css
This finishes the job for the index file, except for icons/sprites, which requires some more thinking.
> CSS segregation, Part IV

- themes/default/css/admin.css
In this section, lines that are too long roll over to the next line, thus breaking the look and format.
> Group Theme Options - Corrects splitting of line.

- sources/Load.php
- sources/controllers/Memberlist.controller.php
- sources/controllers/Register.controller.php
- sources/controllers/Stats.controller.php
- sources/subs/Members.subs.php
- themes/default/GenericBoards.template.php
- themes/default/Memberlist.template.php
- themes/default/css/index.css
<del>Just sending it so that is tracked that few issues are fixed.
I'll add more, so do not merge it yet. ;)</del>
Okay, for now I'm done.
> Some fixes for 1.0.6 on the way to 1.0.7

- sources/subs/Boards.subs.php
- sources/subs/SettingsForm.class.php
- sources/subs/Topic.subs.php
- themes/default/ManageNews.template.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Just another batch of fixes for 1.0.7
> Next 1.0.7 batch-o-fixes

- sources/Load.php
A little tweak to the integrare_avatar call, to make it more flexible and reliable.
> Avatar hook

- sources/AttachmentErrorContext.class.php
- sources/controllers/Attachment.controller.php
- sources/controllers/Display.controller.php
- sources/controllers/Draft.controller.php
- sources/controllers/Post.controller.php
- sources/modules/Attachments/AttachmentsPostModule.class.php
- sources/subs/BBC/Codes.class.php
- sources/subs/Ila.integrate.php
- themes/default/Display.template.php
- themes/default/scripts/post.js
- themes/default/scripts/script_elk.js
And this time seems it's for real!!
It seem it's working as expected on <del>all</del> most of the cases! :joy_cat: 
The only edge case it's not working properly at all is delete temporary attachments without js enabled... very, very low priority edge case to me.
Unless something else **big** comes out, to me ILA are ready to :ship:
> More fixes for in-line attachments

- themes/default/Theme.php
- themes/default/css/_light/index_light.css
- themes/default/css/_light/rtl_light.css
- themes/default/css/index.css
- themes/default/index.template.php
also adding the relevant icons in the embedded css portion. This pretty much rounds out the 'prime' icons.
There's probably some discussion to be had about color and icon choices. Mostly just focused on finding something tolerable for now.
> Some tweaks and cleanup, turns data-icon into a class specifier

- sources/Load.php
- sources/admin/ManageBans.controller.php
- sources/controllers/Display.controller.php
- sources/subs/Cache.subs.php
Signed-off-by: emanuele <emanuele45@gmail.com>
> Fix approval warning in quick-reply - fixes #2457

- sources/Subs.php
- themes/default/scripts/elk_jquery_embed.js
Adding a new hook and "backporting" @Frenzie's code for embedding.
This time sending the PR to the correct branch... :blush:
> The very last few bits for 1.0.7

- themes/default/scripts/elk_jquery_embed.js
Added support for YouTube timestamps and refactored the code a little to get rid of redundancy.
> Youtube timestamps

- install/CommonCode.php
> Fix opcache_invalidate oversight

- install/install_1-1.php
- install/upgrade_1-1.php
- sources/subs/HttpReq.class.php
- themes/default/css/index.css
Just a few basic fixes I did while trying to setup proper e-mail testing.
> Some small fixes. Closes #2459

- install/ToRefactorCode.php
- install/installcore.php
- install/upgrade.php
- install/upgrade_1-1.php
- sources/Load.php
- sources/database/Db-abstract.class.php
- sources/database/Db-mysql.class.php
- sources/database/Db-postgresql.class.php
- sources/subs/EventManager.class.php
- sources/subs/Messages.subs.php
Fixes #2488
Then drops a couple of globals from the db class
> Some upgrade fixes and a couple of changes

- bootstrap.php
- index.php
- install/upgrade_1-1.php
- sources/controllers/Attachment.controller.php
- sources/controllers/News.controller.php
- sources/controllers/PersonalMessage.controller.php
- sources/controllers/ProfileInfo.controller.php
- sources/controllers/Recent.controller.php
- sources/controllers/Who.controller.php
- sources/database/Db-abstract.class.php
- sources/database/Db-mysql.class.php
- sources/database/Db-postgresql.class.php
- sources/subs/CacheMethod/Zend.php
- sources/subs/Likes.subs.php
- sources/subs/Post.subs.php
- sources/subs/Recent.subs.php
- sources/subs/Topic.subs.php
- sources/subs/TopicUtil.class.php
- sources/subs/UserNotification.integrate.php
- themes/default/Theme.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
- themes/default/index.template.php
Another round of fixes for 1.1
> Moar fixes

- install/upgrade_1-1.php
- sources/controllers/Attachment.controller.php
- sources/controllers/Who.controller.php
- sources/database/Db-abstract.class.php
- sources/database/Db-mysql.class.php
- sources/database/Db-postgresql.class.php
- sources/subs/BBC/BBCParser.class.php
- tests/travis-ci/setup_pgsql.php
Just a couple of very smallish ones.
> A tiny one

- themes/default/languages/english/EmailTemplates.english.php
- themes/default/languages/english/ManageSettings.english.php
Also dropped unused strings for dropped caching methods
> A few minor language fixes

- themes/default/css/_light/index_light.css
- themes/default/css/index.css
- themes/default/index.template.php
1) Use the 'new' shade of green for newness. A bit less neon >_>
2) Removed shadows as requested, left in comments.
3) Fixing some styling things that you were starting to get carried away with. <_<
4) Menu button icon sizes - we should change this through the size of the buttons themselves (or the size of the default font). More than 1.5em means buttons with icons will be oversized compared to buttons without.
On the last point - do we want to switch to a full 16px 1em font size? I know many of my forum members would prefer that, and some of yours do as well apparently.
> Some styling fixes

- sources/controllers/Memberlist.controller.php
- themes/default/GenericMessages.template.php
- themes/default/ManageMembergroups.template.php
- themes/default/Memberlist.template.php
- themes/default/ProfileInfo.template.php
- themes/default/ProfileOptions.template.php
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
- themes/default/index.template.php
Please review before merging.
1) The e-mail stuff straddles the line between 'bug fix' and 'unwanted additional exposure'
2) I wasn't sure where I should put the template bits, so I stuck them in index for now. Had difficulty parsing what you were doing.
> Fixing oops, templatelets for e-mail and online status

- install/install_1-1.php
- install/upgrade_1-1.php
- sources/modules/Drafts/DraftsPostModule.class.php
- sources/subs/Attachments.subs.php
- sources/subs/Subscriptions-PayPal.class.php
- themes/default/scripts/mentioning.js
I'm out of ideas for branch names...
> Small fixes

- sources/subs/Package.subs.php
This incidentally fixes the backups being incomplete.
This also creates the uncompressed tarball on the filesystem and I don't know how to get rid of it.  unlink() gives a "permission denied" error.
> New package backup method

- composer.json
- install/upgrade_1-1.php
- release_tools/build.sh
This is also a test for the automatic triggering of Sensiolabs Insight code analysis at https://insight.sensiolabs.com/projects/92bca775-5e4e-4288-9fd5-9cbb660280ac
This PR should generate the 6th analysis.
> Some improvements to the build process + a fix

- themes/default/languages/english/Post.english.php
> Start sentence with a capital letter

- .travis.yml
repositories enabled in 2015 or later must have this line
> Allow forks to initiate their own builds

- themes/default/languages/english/index.english.php
Single thoughts should be on one line - something about good grammar.
Closes #2317
> These links are related

- index.php
- sources/SiteDispatcher.class.php
- tests/sources/DispatcherTest.php
This is my go at cleaning up one of the most important files in Elkarte.
A fool's work is never done, though.
> More cleanup of the site dispatcher

- sources/subs/Package.subs.php
Finally figured out how to delete the uncompressed tarball .
#2553
> Fixes bug introduced in 908f99d2ac38565010b009d29c20b2a39c3483a8

- sources/controllers/Reminder.controller.php
> Must validate that lonely patron; they lost their password!

- sources/subs/Admin.subs.php
> Set the display cache for the custom profile fields

- SSI.php
- sources/Session.php
- sources/ext/serialize.php
- sources/subs/ScheduledTasks.subs.php
Still pending the patch and some other stuff.
> The fixes that fix the 1.0.8 version

- install/patch_1-0-9/modifications.xml
Directly to master because the branch is already merged
> Fix mistake in 1.0.9 patch

- install/patch_1-0-9/modifications.xml
Directly to master because the branch is already merged
> Fix another mistake in 1.0.9 patch

- SSI.php
- sources/Load.php
- sources/subs/Poll.subs.php
- ssi_examples.php
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Was trying to get into this again, got through some easy stuff. Want to push at least this before beta 2 >_>
> Some low-hanging icon fruit.

- sources/subs/DataValidator.class.php
- tests/sources/subs/DataValidator.class.Test.php
>  Data_Validator should send all errors for arrays/csv

- sources/subs/Cache.class.php
- sources/subs/CacheMethod/Filebased.php
> Don't assume cached files are present

- sources/subs/Stats.subs.php
> user offsets can be floats

- sources/subs/Cache.class.php
- sources/subs/CacheMethod/Filebased.php
- themes/default/PersonalMessage.template.php
- themes/default/scripts/PersonalMessage.js
> JSON doesn't want to parse objects twice

- sources/Errors.php
> More duplicates

- sources/admin/ManageAttachments.controller.php
- sources/controllers/Calendar.controller.php
- themes/default/Post.template.php
@Spuds have a look if this solves the error posting an event
> Fix event posting

- sources/subs/PersonalMessage.subs.php
In reference to https://github.com/elkarte/Elkarte/issues/2697
Signed-off-by: Archer70 <code.archer70@gmail.com>
> Move PM integration hook.

- themes/default/css/index.css
- themes/default/scripts/topic.js
> Adjust lightbox for mobile concerns

- sources/admin/PackageServers.controller.php
Since ```filter_var('javascript://test%0Aalert(321)', FILTER_VALIDATE_URL)``` returns true, lets restrict the scheme as well.
> restrict url check a bit more

- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
This fixes the font stack issue and adjusts a few things as noted
> Few theme tweaks

- sources/controllers/Unread.controller.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/index.css
- themes/default/css/jquery.sceditor.css
Menu Icons (large screen and small screen)
Missing global
> Couple of B3 quick fixes

- SSI.php
- install/CommonCode.php
- install/Install_Controller.php
- sources/Subs.php
- sources/admin/Admin.controller.php
- sources/admin/ManageBoards.controller.php
- sources/admin/ManageMaillist.controller.php
- sources/controllers/Display.controller.php
- sources/controllers/ModerationCenter.controller.php
- sources/controllers/PersonalMessage.controller.php
- sources/controllers/ProfileOptions.controller.php
- sources/controllers/Reminder.controller.php
- sources/controllers/Search.controller.php
- sources/database/Db-mysql.class.php
- sources/database/Db-postgresql.class.php
- sources/subs/Attachments.subs.php
- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
- sources/subs/FtpConnection.class.php
- sources/subs/Mail.subs.php
- sources/subs/Members.subs.php
- sources/subs/Menu.subs.php
- sources/subs/Notification.subs.php
- sources/subs/OpenID.subs.php
- sources/subs/Package.subs.php
- sources/subs/Post.subs.php
- sources/subs/Profile.subs.php
- sources/subs/Server.subs.php
Hello.
Looks like there were some non-strict boolean comparisons. In order to mitigate bug risks and improve performance, I implemented strict comparison to booleans. 
Thank you.
> Implemented strict boolean comparison

- sources/admin/AdminLog.controller.php
> Fix call to undefined method

- sources/admin/ManageSearch.controller.php
Now when you add URL addresses in will not be replaced by the symbol **_&_** for the new search engine.
> Fix search engine url

- SSI.php
Split that fugly query yet again. This is some code I made for a client a while ago. Originally for SMF, but I  imagine that Elk uses the same process here. **This is untested.**
This query could be further refined, the joins on the members table could be replaced with `loadMemberContext()`, though that may not be ideal as it can add too much complexity, not sure if worth it.
> Split a query for SSI recent topics

- sources/controllers/Recent.controller.php
- sources/subs/Likes.subs.php
- sources/subs/ManagePermissions.subs.php
- themes/default/index.template.php
Like it says, adds the ability to like a post from the recent listing page.  All because I got distracted on https://github.com/elkarte/Elkarte/issues/2756
> Like posts from recent post listing

- sources/subs/Menu.subs.php
- tests/sources/subs/Menu.subs.Test.php
"Port" back a couple of updates from the defunct menu.class pr
Please check https://github.com/elkarte/Elkarte/pull/2761/commits/1f32ca61be3c7e3612ce7d288aceea7692256f3e as what was there seems like an error to me, possibly left over from the first attempt to clean up this sub.
> Port menu.subs tests from canceled menu.class PR

- sources/admin/Admin.controller.php
- sources/subs/AdminSettingsSearch.class.php
- tests/sources/AdminSearchTest.php
- tests/travis-ci/bootstrap.php
- themes/default/Admin.template.php
> Fix and test internal admin search

- sources/BrowserDetector.class.php
- sources/Load.php
- sources/Subs.php
- sources/admin/ManageFeatures.controller.php
- sources/admin/ManageRegistration.controller.php
- sources/admin/ManageSearch.controller.php
- sources/database/Db-abstract.class.php
- sources/subs/AddonSettings.subs.php
- sources/subs/AdminSettingsSearch.class.php
- sources/subs/BBC/BBCParser.class.php
- sources/subs/CacheMethod/Filebased.php
- sources/subs/CacheMethod/Xcache.php
- sources/subs/ManageAttachments.subs.php
- sources/subs/ManageFeatures.subs.php
- sources/subs/ManageSearch.subs.php
- sources/subs/Messages.subs.php
- sources/subs/Priority.class.php
- sources/subs/Search/Search.php
- sources/subs/VerificationControls.class.php
- themes/default/Display.template.php
- themes/default/GenericMessages.template.php
- themes/default/Register.template.php
- themes/default/languages/english/Login.english.php
- themes/default/languages/english/index.english.php
A few more minor things, some bugs, some tweaks for scruit
> Minor Fixes

- sources/Subs.php
- sources/subs/BBC/Codes.class.php
- sources/subs/Errors/ErrorHandler.php
> Patching a bit the protocol stuff

- sources/Load.php
- sources/admin/ManageSearch.controller.php
- Order of conditions to prevent Notice error
- sphinx search tests were broken
Sphinx seems to be messed up a bit, will check this for RC1 ... this fix just allows the test connection to work again.
> Couple of late fixes

- themes/default/Display.template.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
This was discussed here: http://www.elkarte.net/community/index.php?topic=3739.msg26506#msg26506
It improves the layout and behavior of the below post thumbnails.  We considered it for 1.0.8 but never implemented it.  So here it is, now we can make a decision.
> Improved attachment thumbnail below post code

- install/install_1-1.php
> fix bug profile fields changes

- install/CommonCode.php
- install/DatabaseCode.php
- install/LegacyCode.php
- install/TemplateUpgrade.php
- install/ToRefactorCode.php
- install/upgrade.php
- install/upgrade_1-1.php
Found a few minor things in the 1.1 upgrade ... most of that is 
https://github.com/Spuds/Elkarte/commit/431067464526d02185763a026b0d2eccbe5a9ffa the rest of this  PR is predominantly formatting except for one case where we appear to have overwritten $db
Now the odd thing is this runs fine from the command line but sometimes seems to "stall and die" with the web interface.  No idea why, its just part of the "wonder" that can be found in this script.
> Upgrade updates

- SSI.php
- sources/Request.php
- sources/ext/PasswordHash.php
- sources/subs/Package.subs.php
- sources/subs/Util.class.php
Couple of more items for 1.0.10 ... lets see if scruit fires on this one (which through much pain its working again)
> minor 1.0.10 adjustments

- themes/default/Display.template.php
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Not sure we want this, but it was a question on the forum.  I like it,  but then all my taste is in my mouth !
> Add a #new line to separate posts

- install/install_1-1.php
- sources/controllers/Register.controller.php
- sources/subs/Members.subs.php
- themes/default/Register.template.php
- themes/default/languages/english/index.english.php
This was discussed [here](http://www.elkarte.net/community/index.php?topic=4194.msg30208#msg30208) 
This also sets  the default to off for new 1.1 installs.
> Add "opt-in/out" checkbox at registration

- sources/subs/PackagesFilterIterator.class.php
As discussed in here
http://www.elkarte.net/community/index.php?topic=4261.0
signed off by Ahmad Rasyid Ismail "ahrasis" ahrasis@gmail.com
> file_exists(): open_basedir error fix

- themes/default/Admin.template.php
BBC code list was a messed up due to class being on the wrong element.
> ! class was applied to the wrong element

- sources/subs/BBC/BBCParser.php
- sources/subs/Html2Md.class.php
- tests/sources/subs/BBC.subs.Test.php
- themes/default/Register.template.php
- themes/default/css/index.css
- themes/default/scripts/script_elk.js
- Update how html2md handles multi byte characters for some server/lib-xml combos.
- Named anchor links were fighting collapsing code blocks on page load, causing missed navigation
- Boom
> Markdown changes from 1.0.10 + bugs

- sources/subs/BBC/BBCParser.php
- tests/sources/subs/BBC.subs.Test.php
- tests/travis-ci/setup-server.sh
Moved the smiley marker to wrap the entire added footnote content.
Added a 3rd testcase with a smile before inside and after the footnote
Fixed the signature error for mysql <> 5.5
> Footnotes and smileys were not working

- sources/subs/Graphics.subs.php
- themes/default/scripts/jquery.sceditor.elkarte.js
Editor was stripping tags wrapping center tag (if those tags were not also inside a block tag)
Conversion from png->jpg thumbnails via Imagick were not flatting the alpha channel properly.
> More tweaks

- sources/Autoloader.class.php
- tests/travis-ci/setup-server.sh
http://www.elkarte.net/community/index.php?topic=4204.msg30163#msg30163
@emanuele45 has been slacking 😛 
(talking to oneself in the third person is a sign of the utmost confidence)
> Correctly autoload addon integration files

- sources/admin/ManageSearch.controller.php
- themes/default/ManageSearch.template.php
Well pretty much screwed the 🐩 on that one ... Few other than me use this, but it should at least work.
@emanuele45 these two quick fixes should, if possible, be added to the official patch.  If its to late thats kind of fine as well, but I messed up bringing it in from 1.1, or I messed it up in 1.1 as well LOL
> ! bad backport from 1.1, or maybe bad in 1.1 as well :innocent:

- themes/default/GenericMessages.template.php
> implement negative karma fix in GenericMessages.template.php

- install/install_1-1.php
> fix instagram field icon

- bootstrap.php
Fixed bug where its not set when calling bootstrap.php and therefor tries to use mysql as a default
> Added $db_type to bootstrap.php 

- sources/Security.php
- sources/Subs.php
- sources/admin/ManageSearch.controller.php
- sources/controllers/Auth.controller.php
- sources/modules/Random/RandomPostModule.class.php
- sources/subs/ManageSearch.subs.php
- themes/default/Admin.template.php
> Other fixes

- sources/subs/Maintenance.subs.php
- themes/default/Display.template.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
A couple of SVG's not working in FX
Old "on click" was interfering with js .on used in theme
Clean up ancient query
> Couple of minor fixes

- sources/Subs.php
- sources/Templates.class.php
- sources/controllers/Attachment.controller.php
- sources/controllers/Calendar.controller.php
- sources/controllers/Jslocale.controller.php
- sources/controllers/News.controller.php
- sources/controllers/OpenID.controller.php
- sources/database/Db-mysql.class.php
- sources/subs/Graphics.subs.php
- themes/default/css/index.css
I wouldn't text the Imagick part... if you can please do so. :innocent: 
Also, while writing it, I had the funny idea to have an exception class able to render the error message as image. Maybe in the future.
> Some more bugz :P

- sources/Session.php
- sources/subs/Graphics.subs.php
- sources/subs/SessionHandler/DatabaseHandler.php
- Updates session db write function to return true and drop the microtime #2933 
- Update the image security checks, normal is just php injection, paranoid is < the old normal (php, scirpt and flash) should be less false hits and unnecessary re-encoding #2874 
- Added TT support to the generateTextImage GD functions.  The IM section needed some updates to return the image string vs output right away. broke the two in to separate functions.
> A few items, some questionable :D

- sources/controllers/Attachment.controller.php
- sources/controllers/ProfileInfo.controller.php
- sources/database/Db-abstract.class.php
- sources/database/Db-postgresql.class.php
- sources/subs/AdminSettingsSearch.class.php
- sources/subs/Graphics.subs.php
- tests/sources/admin/AdminSearchTest.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/languages/english/Profile.english.php
Few minor fixes and one minor "add" ... I'd detail them here for future generations to read, but why when you can just read the self explanatory, and creative narratives in the commits ?
> Fix some, add some

- sources/controllers/ProfileInfo.controller.php
- themes/default/css/index.css
This adds thumbnail images to the user attachment list.
> Add thumbs to recent attachment listing

- themes/default/scripts/theme.js
- themes/default/scripts/topic.js
This should add basic arrow navigation to the poor man lightbox.  This has been asked for often enough that I thought we should try to add something.  
Looks like a bigger change than it is as some existing code was moved to var functions so they could be called multiple times for navigation.  This only works with the right and left arrows, there are not graphical items to click.
> Another experiment

- sources/AbstractModel.php
- sources/ValuesContainer.php
- sources/subs/Errors/Errors.php
- sources/subs/Errors/Log.php
- sources/subs/Notifications.class.php
- sources/subs/PbeImap.class.php
What do you think about it @Spuds ? :angel: 
```
$value = $AbstractModel->_modSettings->aProp;
```
$value either gets the value of aProp, or null
```
$value = $AbstractModel->_modSettings->aProp('default_value');
```
$value either gets the value of aProp, or 'default_value'
> A little experiment

- themes/default/scripts/elk_jquery_embed.js
See http://www.elkarte.net/community/index.php?topic=4633.0
> elk_jquery_embed.js: add m.youtube.com handler

- sources/controllers/BoardIndex.controller.php
- sources/subs/Ila.integrate.php
- sources/subs/MentionType/BuddyMention.php
- sources/subs/MentionType/MentionTypeInterface.php
- themes/default/GenericControls.template.php
- themes/default/ManageMembergroups.template.php
- themes/default/css/index.css
- themes/default/css/rtl.css
- themes/default/scripts/dropAttachments.js
- themes/default/scripts/jquery.sceditor.elkarte.js
Whoa ... I actually took the time to PR this LOL
> Pure excitement here

- sources/SiteDispatcher.class.php
- sources/subs/BBC/Codes.php
- sources/subs/Errors/ErrorHandler.php
- sources/subs/Ila.integrate.php
- sources/subs/ManageFeatures.subs.php
Added a enable method for parse for tags that were disabled on the fly by and addon.  Since we have a single instance of the class, disable / enable functions are needed.
Then a few small fixes for ILA, probably more to come :P selling and debug message improvement for moi
> My patch1 1 1

- install/upgrade.php
- install/upgrade_1-1.php
- sources/subs/BBC/HtmlParser.php
- sources/subs/ManageFeatures.subs.php
- sources/subs/Profile.subs.php
- tests/sources/subs/BBC.subs.Test.php
- tests/sources/subs/BBCHTML.subs.Test.php
- themes/default/languages/english/LikePosts.english.php
- themes/default/languages/english/UserNotifications.english.php
And some that is actually just nice to have.
> Some more stuff that need to be fixed in 1.1

- sources/subs/Graphics.subs.php
Also make sure Imagick respects that flag.  Both changes will help with the proxy as well.
> Allow resizeImageFile to also passthru force_resize param

- bootstrap.php
- release_tools/generate_detailed-version.php
- sources/Load.php
- sources/subs/Admin.subs.php
- sources/subs/BBC/Codes.php
- sources/subs/BBC/HtmlParser.php
- sources/subs/Errors/ErrorHandler.php
- sources/subs/ManageFeatures.subs.php
- sources/subs/Moderation.subs.php
- sources/subs/Profile.subs.php
- themes/default/Theme.php
Related to the #3063 issue I opened before.
> Updated the release tools and related functions

- sources/subs/Themes/Templates.php
- sources/subs/Themes/ThemeLoader.php
@live627 I found these two commits lost in your refactoring, if you have time, have a look if there is something else. I suspect you branched at 1.1 RC1 time (or close) and due to the changes in the name of files some of the fixes were overwritten.
> Restore lost commits

- sources/subs/Themes/TemplateLayers.php
- themes/default/Theme.php
Lost in 85f862a2b0a7c6774cf06ca07f02ef2800d8d327
> Restore error safe layers

- sources/admin/ManageMembers.controller.php
- sources/controllers/ProfileInfo.controller.php
- sources/subs/Action.class.php
This should be a lot easier for people to sift thru
> refactor action dispatcher

- sources/Subs.php
- sources/admin/ManageFeatures.controller.php
- sources/controllers/ProfileOptions.controller.php
- sources/subs/BBC/BBCParser.php
- sources/subs/Errors/Errors.php
- sources/subs/Graphics.subs.php
- sources/subs/Who.subs.php
- themes/default/Theme.php
This commit consists of patches automatically generated for this project on https://scrutinizer-ci.com
> Scrutinizer Auto-Fixes

- sources/ext/bad-behavior/bad-behavior/core.inc.php
- sources/ext/bad-behavior/bad-behavior/screener.inc.php
- sources/ext/bad-behavior/badbehavior-plugin.php
> Removed backticks and updated to latest version of badbehaviour

- sources/Load.php
- sources/subs/Errors/Errors.php
- sources/subs/Exception/ElkException.class.php
- themes/default/css/index.css
There is still another potential issue here:
https://github.com/elkarte/Elkarte/blob/1c2044d6c6f58f6f5f9b713c9872c8a56bd0de4d/sources/Request.php#L425-L430
I don't think "http" in the query is **so** evil, provided the parser doesn't have other flaws.
Do you think it should be kept or it can be dropped?
> Dealing with early errors

- install/install_1-1.php
- install/upgrade_1-1.php
- sources/Load.php
- sources/admin/ManageFeatures.controller.php
- sources/controllers/Recent.controller.php
- sources/subs/Ila.integrate.php
- sources/subs/Memberlist.subs.php
- sources/subs/Profile.subs.php
- themes/default/ManageFeatures.template.php
- themes/default/css/admin.css
- themes/default/css/icons_svg.css
- themes/default/languages/english/Admin.english.php
- themes/default/languages/english/Help.english.php
- themes/default/scripts/admin.js
I put this together in a very not linear way, I started implementing it as key/val pairs stored in encoded json strings, then I moved to use the numeri key of the array.
I hope I cleaned up everything, but I'm not terribly sure of it, so anyone reviewing it: do it twice. :laughing: 
The upgrade doesn't fix the existing fields in order not to break anything that potentially already exist (i.e. if it is broken, it's easy to fix, if we broke it now it's worse).
> And here it is: allow using the keys as substitution parameter for radio and select custom fields

- composer.json
update to point to https sites 
remove version line since its prone us not updating it (and its not needed)
update description
use recommended license name
> Minor updates for packlist

- SSI.php
- sources/Subs.php
- sources/admin/ManageAttachments.controller.php
- sources/ext/serialize.php
- sources/subs/EmailFormat.class.php
- sources/subs/ScheduledTask/Birthdayemails.php
- ssi_examples.php
- themes/default/css/jquery.ui.tabs.css
Picked off a few more of the bugs.  updated some SSI (one bug, the rest formatting) so the examples file worked better.  I think both files could simply be replaced in the upgrade.
> A few more fixes for 1.1.4

- sources/subs/Ila.integrate.php
- themes/default/css/index.css
- themes/default/css/rtl.css
This should fix the ILA issue with plain attach tags.
Still have the >100K issue, I found the one problem that it only checks for new replys on a single board instead of all boards, we should consider adding that fix as well.
> Last *cough* of the 1.1.4 things

- bootstrap.php
Parital fix for installer, check to make sure either install.php or upgrade.php exists before redirecting.
> Check to make sure either install.php or upgrade.php exists before redirecting

- sources/admin/Packages.controller.php
- sources/controllers/Attachment.controller.php
- sources/controllers/Post.controller.php
- sources/controllers/ProfileHistory.controller.php
- sources/controllers/Register.controller.php
- sources/modules/Calendar/CalendarPostModule.class.php
- sources/subs/CalendarEvent.class.php
- sources/subs/Graphics.subs.php
- sources/subs/Search/API/Sphinxql.php
- sources/subs/VerificationControls.class.php
- tests/travis-ci/setup-server.sh
- themes/default/Post.template.php
- themes/default/VerificationControls.template.php
- themes/default/css/index.css
- themes/default/languages/english/LikePosts.english.php
- themes/default/languages/english/ManageSettings.english.php
- themes/default/scripts/jquery.captcha.js
- themes/default/scripts/like_posts.js
> Some Fixes for 1.1.6

- install/Install_Controller.php
- themes/default/scripts/mentioning.plugin.js
Trying to close out what we can
> A couple of more 1.1.6 fixes

- SSI.php
- install/install.php
- sources/subs/Recent.class.php
- sources/subs/Search/Search.php
@Spuds please have a look at the search part, I *think* it should work, but with search you never know. :laughing:
> The two "security" issues open

- sources/Session.php
This is a suggested update to secure PHPSESSIONID as discussed in https://www.elkarte.net/community/index.php?topic=5596.0
> Update Session.php to secure PHPSESSIONID

- SSI.php
- sources/admin/ManageSearch.controller.php
- sources/subs/Members.subs.php
- sources/subs/Permissions.class.php
- subscriptions.php
- tests/sources/subs/Permissions.class.Test.php
Sorry for the last second bonus fixes, but there were some soft errors to clean up.
> Updates to permissions class

- sources/admin/ManageBans.controller.php
- sources/subs/BoardsList.class.php
- sources/subs/Post.subs.php
Going to sneak this in 👼   One is "nice: the other is really a bug and potentially a bad one.
> Shhh, last second tweaks are the best

- sources/admin/ManagePermissions.controller.php
Not sure if there is time or not ... but here it is !
> Yet another late fix

- .travis.yml
- sources/ElkArte/Http/StreamFetchWebdata.php
- sources/ElkArte/Subscriptions/PaymentGateway/Authorize/Payment.php
- sources/ElkArte/Subscriptions/PaymentGateway/PayPal/Payment.php
- sources/ElkArte/Subscriptions/PaymentGateway/PaymentInterface.php
- sources/ElkArte/Subscriptions/PaymentGateway/TwoCheckOut/Payment.php
- sources/subs/Members.subs.php
- tests/sources/controllers/RegisterWeb.php
- tests/sources/subs/Http/Curl_Fetch_Webdata.class.Test.php
- tests/sources/subs/Http/Fsock_Fetch_Webdata.class.Test.php
- tests/sources/subs/Http/Stream_Fetch_Webdata.class.Test.php
- tests/sources/subs/Permissions.class.Test.php
- tests/travis-ci/setup-server.sh
- themes/default/scripts/admin.js
- themes/default/scripts/drafts.plugin.js
- themes/default/scripts/mentioning.plugin.js
- themes/default/scripts/script.js
- themes/default/scripts/script_elk.js
First this moves from trusty to xenial for the tests, this mainly due to trusty's issues with getting mysql 5.7 installed and since thats the default for xenial ....
Fixed a few legit errors in the code that the tests were failing on
Made some changes so jshint will give us a clean pass, I *did* supress 2 errors with todo's in the code.  There were 2 functions inside of loops that I just did not want to deal with right now.
So this passes on my local, lets see what it does here.
> Travis testbed updates and other fixes

- sources/ElkArte/AdminController/ManageAttachments.php
- sources/ElkArte/AdminController/Packages.php
- sources/ElkArte/AttachmentsDirectory.php
- sources/ElkArte/ScheduledTasks/Tasks/RemoveTempAttachments.php
- sources/Load.php
- sources/subs/Attachments.subs.php
- sources/subs/Emailpost.subs.php
- sources/subs/ManageAttachments.subs.php
Since the first was merged, this is a second step.
Nothing tested for the moment.
> Attachments round 2

- sources/controllers/PersonalMessage.controller.php
- sources/ext/bad-behavior/badbehavior-plugin.php
- sources/subs/Attachments.subs.php
- themes/default/Display.template.php
- themes/default/index.template.php
Fix a couple of more bugs in the list and some unreported minor items needing cleanup.
> More 1.1.7 updates /  fixes

- .codecov.yaml
- .codecov.yml
- sources/subs/Drafts.subs.php
- sources/subs/Emailpost.subs.php
- tests/sources/admin/PackagesTest.php
- tests/sources/controllers/AttachmentTest.php
- tests/sources/controllers/AuthTest.php
- tests/sources/controllers/DraftTest.php
- tests/sources/controllers/EmailUserTest.php
- tests/sources/controllers/EmailpostTest.php
- tests/sources/controllers/HelpTest.php
- tests/sources/controllers/MarkReadTest.php
- tests/sources/controllers/MemberListTest.php
- tests/sources/controllers/ModerationCenterTest.php
- tests/sources/controllers/PersonalMessageTest.php
- tests/sources/subs/BBC.subs.Test.php
- tests/sources/subs/DataValidator.class.Test.php
- tests/travis-ci/setup-results.sh
been having some trouble with scrutinizer not finding the coverage report (TT is open with them).  In the meantime figured I try other options.  First attempted codacy but .... now lets try codecov to see what it does
> Lets see what CodeCov can do

- sources/ElkArte/AdminController/ManageAttachments.php
- sources/ElkArte/AttachmentsDirectory.php
- sources/ElkArte/Controller/Attachment.php
- sources/ElkArte/Controller/Display.php
- sources/ElkArte/Modules/Attachments/Post.php
- sources/ElkArte/TemporaryAttachment.php
- sources/ElkArte/TemporaryAttachments.php
- sources/ElkArte/TemporaryAttachmentsList.php
- sources/ElkArte/ValuesContainer.php
- sources/subs/Attachments.subs.php
- sources/subs/Emailpost.subs.php
- sources/subs/Profile.subs.php
- themes/default/languages/english/Admin.english.php
- themes/default/languages/english/Help.english.php
It's just kind of masking the complexity, though... well it makes code a bit more easy (maybe).
The idea is similar to what I did in the past with another session variable: a sort of wrapper around $_SESSION['temp_attachments'] with the bonus of moving some methods to the class allowing for some work once spread around to be now in a single place.
Still requires some work. :stuck_out_tongue: (And a lot of documentation blocks lol)
Up for comments!
> [WIP] First round of miving the management of temporary attachments to its own class

- sources/ElkArte/ScheduledTasks/Tasks/RemoveTempAttachments.php
- sources/subs/Emailpost.subs.php
- sources/subs/ManageAttachments.subs.php
!Fixed undefined $attachmentDirectory changed to $attachmentsDir
Signed-off-by: Jonathan <vbgamer45@gmail.com>
> Fixes undefined $attachmentDirectory changed to $attachmentsDir

- .github/dependabot.yml
Get automated pull requests for dependency updates like this one https://github.com/live627/Elkarte/pull/10
> Go, go, dependabot, go!

- sources/subs/Auth.subs.php
This does not provide any ACP setting, this just defaults the samesite value to Lax which is what browsers are doing anyway.  Should someone even need to change this they can use the integration hook or call the function directly, or make the edit.  This setting is a 7.3+ thing (without hacks)  so pre 7.3 its not sent.
In 2.0 we could perhaps add an ACP setting, I'm just don't think it necessary.
> Add samesite parameter to set cookie

- sources/admin/ManageAttachments.controller.php
This should fix #3346
I think the main issues were
1. you can't have use of subdirectories when in manual mode.
2. There was an error in the settings such that the attachmentUploadDir text box was never active and it should have been under certain conditions.  Those conditions had been previously moved in the code but the settings check had not been updated.  Fixing that allows the troublesome code block to run when intended.
3. when removing attachment directories when you got back to "the as installed" state, the system did not revert to the as installed behavior,  This due to the empty directory state being written as an empty serialize array vs just plain empty.
No of that may make any sense, or if  other errors still exist, but as anyone who has looked into the area knows, its not …
> Fix multiple issues / annoyances in manage attachments

- sources/BrowserDetector.class.php
- sources/Debug.class.php
- sources/Subs.php
- sources/admin/ManageCalendarModule.controller.php
- sources/admin/ManageErrors.controller.php
- sources/admin/ManageSmileys.controller.php
- sources/controllers/Xml.controller.php
- sources/subs/Compat.subs.php
- sources/subs/Emailpost.subs.php
- sources/subs/Notification.subs.php
- sources/subs/QueryAnalysis.class.php
- sources/subs/SessionHandler/DatabaseHandler.php
- sources/subs/Smileys.subs.php
- themes/default/Maillist.template.php
- themes/default/Notify.template.php
- themes/default/Post.template.php
- themes/default/css/index.css
- themes/default/scripts/script_elk.js
D&D smile would not work when dropping to first postion (I think it was a 7.4 issue)
A couple of misaligned buttons / icons
Missing file header changes
> A few more items

- SSI.php
- install/upgrade.php
- sources/ElkArte/Database/AbstractQuery.php
- sources/ElkArte/Database/Postgresql/Query.php
- sources/ElkArte/Database/QueryInterface.php
- sources/ElkArte/Errors/Log.php
- sources/ElkArte/OpenID.php
- sources/ElkArte/Unread.php
- sources/subs/Attachments.subs.php
- sources/subs/BadBehavior.subs.php
- sources/subs/Bans.subs.php
- sources/subs/Logging.subs.php
- sources/subs/Maintenance.subs.php
- sources/subs/Memberlist.subs.php
- sources/subs/MessageIndex.subs.php
- sources/subs/PaidSubscriptions.subs.php
- sources/subs/PersonalMessage.subs.php
- sources/subs/Post.subs.php
- sources/subs/Recent.subs.php
- sources/subs/ScheduledTasks.subs.php
- sources/subs/SearchEngines.subs.php
- sources/subs/Stats.subs.php
- sources/subs/Themes.subs.php
- sources/subs/Who.subs.php
The original idea was to convert the "query" without identifier to "queryFetch", but I re-scoped to drop the unnecessary identifiers still hanging around.
There are still a few that I'm not sure how to get rid of, though... it's getting closer.
> Query to fetch

- sources/ElkArte/Database/AbstractQuery.php
- sources/ElkArte/Database/Mysqli/Query.php
- sources/ElkArte/Database/Postgresql/Query.php
- sources/ElkArte/Database/Postgresql/Search.php
- sources/ElkArte/Search/API/Custom.php
- sources/ElkArte/Search/API/Fulltext.php
- sources/ElkArte/Search/API/Standard.php
- sources/subs/Calendar.subs.php
- sources/subs/Likes.subs.php
- sources/subs/ManagePermissions.subs.php
- sources/subs/Membergroups.subs.php
- sources/subs/MessageIndex.subs.php
- sources/subs/Notification.subs.php
- sources/subs/Profile.subs.php
- sources/subs/RepairBoards.subs.php
- sources/subs/Stats.subs.php
- sources/subs/Topic.subs.php
> Some db stuff

- sources/ElkArte/Controller/Post.php
- sources/ElkArte/DataValidator.php
- sources/ElkArte/Database/AbstractResult.php
- sources/ElkArte/Database/Mysqli/Table.php
- sources/ElkArte/Database/Postgresql/Table.php
- sources/ElkArte/Database/QueryInterface.php
- sources/ElkArte/Database/SearchInterface.php
- sources/ElkArte/Errors/Errors.php
- sources/ElkArte/HttpReq.php
- sources/ElkArte/IlaIntegrate.php
- sources/ElkArte/Mentions/Mentioning.php
- sources/ElkArte/TokenHash.php
- sources/ElkArte/TopicsMerge.php
- sources/Security.php
- sources/Subs.php
- sources/database/Database.subs.php
- sources/ext/JSqueeze.php
- sources/subs/Admin.subs.php
- sources/subs/Notification.subs.php
- sources/subs/PaidSubscriptions.subs.php
- sources/subs/Poll.subs.php
- sources/subs/Post.subs.php
- sources/subs/Topic.subs.php
- themes/default/ManageMembergroups.template.php
Just another round of breaking up super long post methods to just very long post methods
Included some other items from static analysis and trying to fix docbloc throws methods wich storm seems to like to add to methods even though they don't throw them (cascade effect) which just makes things harder to traverse IMO
> Post Updates

- sources/ElkArte/AttachmentsDirectory.php
- sources/ElkArte/Controller/Attachment.php
- sources/ElkArte/Graphics/Image.php
- sources/ElkArte/Graphics/Manipulators/AbstractManipulator.php
- sources/ElkArte/Graphics/Manipulators/Gd2.php
- sources/ElkArte/Graphics/Manipulators/Imagick.php
- sources/ElkArte/Graphics/TextImage.php
- sources/ElkArte/Modules/Attachments/Post.php
- sources/ElkArte/TemporaryAttachment.php
- sources/ElkArte/TemporaryAttachmentsList.php
- sources/subs/Attachments.subs.php
- sources/subs/ManageAttachments.subs.php
- sources/subs/Messages.subs.php
> Attach updates

- sources/ElkArte/AdminController/ManageSearch.php
- sources/ElkArte/Controller/Search.php
- sources/ElkArte/DataValidator.php
- sources/ElkArte/Database/AbstractSearch.php
- sources/ElkArte/Search/API/Custom.php
- sources/ElkArte/Search/API/Fulltext.php
- sources/ElkArte/Search/API/Standard.php
- sources/ElkArte/Search/SearchParams.php
- sources/subs/ManageSearch.subs.php
- Fixed a couple of errors in search due to previous needed db query refactoring
- consolidates some more duplicate code blokes
- broke up search params large method to many setters and tried to normalize the crazy casting 
- moved to a json encode from the existing php 4.x compatible
- broke some stuff that I have not yet found, but that method had/has some crazy assed conditions!
> Search Updates

- install/install_1-1.php
- install/upgrade_1-1.php
- sources/ElkArte/Controller/Notify.php
- sources/ElkArte/Notifications.php
- sources/ElkArte/Notifiers/Methods/EmailDaily.php
- sources/ElkArte/Notifiers/Methods/EmailWeekly.php
- sources/ElkArte/UrlGenerator/Standard/Standard.php
- sources/subs/Emailpost.subs.php
- sources/subs/Notification.subs.php
- sources/subs/Profile.subs.php
- sources/subs/Topic.subs.php
- tests/sources/subs/Mention.subs.Test.php
- themes/default/ProfileOptions.template.php
@Spuds see if this appears to somehow work.
> Fix broken notification saves in profile area

- sources/ElkArte/AttachmentsDirectory.php
- sources/subs/Stats.subs.php
- tests/install/ElkArteInstallWeb.php
- tests/sources/controllers/AuthWeb.php
- tests/sources/controllers/ElkArteWebSupport.php
- tests/sources/controllers/PostTestWeb.php
- tests/sources/controllers/ProfileForumWeb.php
- tests/sources/controllers/ProfileInfoWeb.php
- tests/sources/controllers/RegisterWeb.php
- tests/sources/controllers/acpAddGroupWeb.php
- tests/sources/controllers/acpManageMembersWeb.php
- tests/sources/subs/Boards.subs.Test.php
More tweaks / changes / consolidation to improve the web test which still fail on a random basis.  Hard to debug too
Tossed in a couple of new test to well ... test
> Additoanl Test tweaks

- themes/default/scripts/jquery.sceditor.elkarte.js
This creates new extended helper functions to eliminate the areas of duplicate/similar code in our editor commands.
> Update SCE Commands

- sources/admin/ManageSearch.controller.php
- sources/subs/ManageSearch.subs.php
- sources/subs/Search/API/Fulltext.php
This will correct the issue in the first instance, although I would prefer to change the topic only search also. 
What tab space do you use on here? As it all aligns on my side but github show's it as not. 
Also, how do I get the search to follow the same path each time? It seems to cache or similar so I never get the same results repeated and I'm yet to work out where that is.
> Change search to look at subject as well as body

- install/CommonCode.php
- install/Db-check-MySQL.php
- install/Install_Controller.php
- install/TemplateInstall.php
- install/install.php
- install/installcore.php
- sources/database/Db-mysql.class.php
- sources/database/Db-postgresql.class.php
- sources/database/Db.php
- sources/database/DbTable-mysql.php
- sources/subs/ManageSearch.subs.php
- sources/subs/MentionType/MentionTypeInterface.php
- sources/subs/MessageTopicIcons.class.php
- sources/subs/Priority.class.php
- sources/subs/RepairBoards.subs.php
- sources/subs/SessionHandler/SessionHandler.php
- sources/subs/SessionHandler/SessionHandlerInterface.php
- themes/default/languages/english/Install.english.php
Custom icon error report on the forum
Minor php8 stuff, still not fully tested
regression error from 1.0 -> 1.1
minor install tweaks
> An a few more fixes for 1.1.7

- sources/ElkArte/AdminController/ManageSearch.php
- sources/ElkArte/Search/API/Fulltext.php
- sources/subs/ManageSearch.subs.php
Seems someone before me didn't use spaces, I'll sort those. 
Edit: seems I can't actually see them in my editor and changing them has no effect.
> Changes to support fulltext on subject

- sources/ElkArte/Database/Mysqli/Result.php
Fixes; https://www.elkarte.net/community/index.php?topic=5822.msg42134#msg42134
This should be clean as I force pushed over my old development copy
> Check to ensure the result is an instance of mysqli_result

- bootstrap.php
- sources/Load.php
Plus allow addons / core to use subdir setting for css/ja
> cleanRequest was happening to soon to clean all requests

- sources/admin/ManageMaillist.controller.php
- sources/admin/ManageMembers.controller.php
- sources/controllers/Mentions.controller.php
- sources/subs/BBC/BBCParser.php
- sources/subs/BBC/Codes.php
- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
- sources/subs/Members.subs.php
> Few more issues for 1.1.7 as marked

- bootstrap.php
- install/TemplateInstall.php
- install/TemplateUpgrade.php
- install/installcore.php
- install/upgrade.php
- install/upgrade_1-1.php
- release_tools/generate_detailed-version.php
- themes/default/css/install.css
Up version level tags
Update the upgrader html so it validates
Add update to fix PBE table before upgrade (that's only a 1.0 to 1.1 upgrade item)
Travis has crapped his pants again so the tests are not running.
> Final bits for 1.1.7

- sources/admin/ManageFeatures.controller.php
- sources/subs/ManageFeatures.subs.php
- themes/default/languages/english/ManageSettings.english.php
per https://www.elkarte.net/community/index.php?topic=6015
> Ability to turn off current action from profile view

- sources/controllers/Attachment.controller.php
- sources/subs/ManageAttachments.subs.php
An unprivileged user could potentially delete an attachment
> Improper Privilege Management

- sources/ElkArte/Http/FsockFetchWebdata.php
- sources/ElkArte/Http/StreamFetchWebdata.php
- tests/sources/subs/Http/Curl_Fetch_Webdata.class.Test.php
- tests/sources/subs/Http/Fsock_Fetch_Webdata.class.Test.php
- tests/sources/subs/Http/Stream_Fetch_Webdata.class.Test.php
Change test endpoints to github url etc
add ssl work arounds to stream fetch
use a common ua.  Not some sites are very sensitive to php/xyz or curl/x.x.x etc
> ! Update test endpoints

- sources/ElkArte/Controller/Post.php
> The followup parameter can come from both a GET or a POST, so... getRequest - fixes #3497

- SSI.php
- install/Install_Controller.php
- sources/DumpDatabase.php
- sources/ElkArte/AdminController/ManageCalendarModule.php
- sources/ElkArte/AdminController/ManagePaid.php
- sources/ElkArte/Agreement.php
- sources/ElkArte/CalendarEvent.php
- sources/ElkArte/Controller/News.php
- sources/ElkArte/Controller/Register.php
- sources/ElkArte/Controller/Stats.php
- sources/ElkArte/Database/Postgresql/Query.php
- sources/ElkArte/Database/Postgresql/Result.php
- sources/ElkArte/Modules/Calendar/Post.php
- sources/ElkArte/Util.php
- sources/Logging.php
- sources/Subs.php
- sources/subs/Calendar.subs.php
- sources/subs/Memberlist.subs.php
- sources/subs/Members.subs.php
- sources/subs/MembersOnline.subs.php
- sources/subs/Package.subs.php
- sources/subs/Profile.subs.php
- sources/subs/SearchEngines.subs.php
- themes/default/Xml.template.php
- themes/default/languages/english/Help.english.php
- themes/default/languages/english/index.english.php
Updates for Postgres and other associated PHP 8.1 changes
> Postgres and PHP 8.1 Fixes 

- sources/ElkArte/Controller/Display.php
- sources/ElkArte/Controller/Recent.php
- themes/default/Display.template.php
- themes/default/css/index.css
- themes/default/scripts/like_posts.js
> Switches Likes to Reacts Elkarte2

- sources/ElkArte/AdminController/ManageRegistration.php
- sources/ElkArte/AdminController/ManageThemes.php
- sources/ElkArte/Controller/Notify.php
- sources/ElkArte/Errors/Errors.php
- sources/ElkArte/Languages/Loader.php
- sources/ElkArte/Modules/Drafts/Profile.php
- sources/ElkArte/ScheduledTasks/Tasks/ApprovalNotification.php
- sources/subs/Mail.subs.php
- sources/subs/Themes.subs.php
@emanuele45  I noticed a couple of typos, here is a quick PR.
> Couple of language loader typo's

- sources/ElkArte/Controller/Display.php
- themes/default/Display.template.php
This is inspired by the QRR addon by @ahrasis done in a 2.0 fashion.  It moves the quick reply area to the bottom of the message list and makes it look like a post area.  See picture.
> Quick Reply Tweaks

- sources/ElkArte/Controller/PersonalMessage.php
- sources/ElkArte/Modules/Drafts/PersonalMessage.php
- sources/subs/Drafts.subs.php
- sources/subs/PersonalMessage.subs.php
- themes/default/GenericControls.template.php
- themes/default/PersonalMessage.template.php
- themes/default/scripts/post.js
Due to the change in api; xml; stuff
Cleaned up a few things as long as I had that controller open.
> PM auto drafts and preview were not working as expected

- .github/LICENSE
- LICENSE
- sources/ElkArte/AdminController/ManageAttachments.php
- sources/ElkArte/AdminController/ManageLanguages.php
- sources/ElkArte/AdminController/ManageSmileys.php
- sources/ElkArte/BBC/BBCParser.php
- sources/ElkArte/Controller/Attachment.php
- sources/ElkArte/Controller/Search.php
- sources/ElkArte/Emoji.php
- sources/ElkArte/FileFunctions.php
- sources/ElkArte/Member.php
- sources/ElkArte/SiteDispatcher.php
- sources/Logging.php
- sources/subs/Profile.subs.php
- sources/subs/Smileys.subs.php
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
Cleaning up some branches ... tests will likely fail due to DDG 403 ... fixed in a PR elsewhere so 🤷 see ya!
> Inconsequential tweaks and minor bug fixes

- install/install_2-0.php
- sources/ElkArte/AdminController/ManageAttachments.php
- sources/ElkArte/AdminController/ManageSecurity.php
- sources/ElkArte/Languages/Loader.php
- sources/subs/Attachments.subs.php
- themes/default/GenericMessages.template.php
- themes/default/Post.template.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_light/index_light.css
- themes/default/css/index.css
- themes/default/scripts/dropAttachments.js
Some trivial fixes found during the pacman attempt
> A few fixes

- sources/ElkArte/AdminController/ManageTopics.php
- sources/ElkArte/Controller/Display.php
- sources/ElkArte/Controller/Stats.php
- sources/ElkArte/Languages/Index/English.php
- sources/ElkArte/Mail/QueueMail.php
- sources/ElkArte/Modules/Poll/Display.php
- sources/ElkArte/Modules/Poll/Post.php
- sources/subs/Recent.subs.php
- sources/subs/Stats.subs.php
- themes/default/Display.template.php
- themes/default/GenericMessages.template.php
- themes/default/Post.template.php
- themes/default/css/index.css
- themes/default/css/rtl.css
- themes/default/scripts/script.js
- themes/default/scripts/script_elk.js
- themes/default/scripts/stats.js
- themes/default/scripts/topic.js
Fix a few items from the site error log
- Polls did not work, were not saved, could not enable/disable the feature
- reducemailqueue was missing required Mail.subs
- undefined error in the poster div creation
- css formatting tweaks
- quick edit was not updating ui when done
- new anchor was in wrong location
- stats were not expanding
> Site Fixes

- sources/ElkArte/BBC/Codes.php
- sources/ElkArte/BBC/PreparseCode.php
- sources/ElkArte/Emoji.php
- sources/Subs.php
- tests/sources/SubsTest.php
- tests/sources/subs/Preparse.subs.Test.php
- tests/sources/subs/SettingsForm.Test.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/_dark/index_dark.css
- themes/default/css/_light/index_light.css
- themes/default/css/_light/jquery.sceditor.elk_wiz_light.css
- themes/default/css/index.css
- themes/default/scripts/emoji.plugin.js
- themes/default/scripts/jquery.sceditor.elkarte.js
Title says what it is .... [icode]some thing awesome[/icode]
> Add new BBC [icode] tag for inline code 

- sources/ElkArte/AdminController/ManageAttachments.php
- sources/ElkArte/Graphics/Image.php
- sources/ElkArte/Graphics/ImageUploadResize.php
- sources/ElkArte/Graphics/Manipulators/AbstractManipulator.php
- sources/ElkArte/Graphics/Manipulators/Imagick.php
- sources/ElkArte/Modules/Attachments/Post.php
- sources/ElkArte/TemporaryAttachment.php
- themes/default/Post.template.php
- themes/default/css/_light/index_light.css
- themes/default/scripts/dropAttachments.js
A couple of webP adjustments.  If the admin does not want to save/transmit webP , but is willing to allow them to be uploaded, then the system will convert them to PNG or JPG (best choice based on input image) IF the server has webP support in the graphics engine.
> webP Adjustments

- sources/subs/BBC/Codes.php
- sources/subs/Bans.subs.php
- sources/subs/EmailParse.class.php
- sources/subs/PackagesFilterIterator.class.php
- sources/subs/Subscriptions-PayPal.class.php
> Version headers

- sources/Logging.php
- sources/QueryString.php
- sources/admin/ManageServer.controller.php
- sources/admin/PackageServers.controller.php
- sources/controllers/Emailpost.controller.php
- sources/controllers/Notify.controller.php
- sources/controllers/Profile.controller.php
- sources/controllers/ProfileHistory.controller.php
- sources/subs/EmailFormat.class.php
- sources/subs/EmailParse.class.php
- sources/subs/Emailpost.subs.php
- sources/subs/Html2BBC.class.php
- sources/subs/Html2Md.class.php
- sources/subs/Notification.subs.php
- sources/subs/Util.class.php
- tests/sources/subs/HTML2BBC.class.Basic.php
- tests/sources/subs/HTML2Md.class.Basic.php
- themes/default/Xml.template.php
- themes/default/css/_besocial/index_besocial.css
- themes/default/css/index.css
- themes/default/scripts/quickQuote.js
Most of this PR is to improve email parsing (much backported from 2.0 based on recent multipart/mixed/related issues) and then conversions to BBC
Also fixed a few items, like tabs missing in the package server page
Improved the way unsubscribe tokens were passed
Profile Edits tab was showing even with core feature off
> 119 Fixes and Improvements

- sources/controllers/Attachment.controller.php
- sources/ext/bad-behavior/badbehavior-plugin.php
- sources/subs/Mail.subs.php
- themes/default/css/index.css
- Need to suppress fsockopen errors in the 1.1 branch or it will not continue (lacks error handler)
- ila with w/h defined in preview could show low resolution image
- BB logging continued to get a surplus ' inserted, lets stop that once and for all
> Additional beta issues

- install/CommonCode.php
- install/Install_Controller.php
- install/install.php
- install/upgrade.php
Changes around the way the settings file was being saved/manipulated as two issues were occurring
1) upgrades would leave the forum in maintenance mode 2 due to strange double update save logic 
2) install would not read in the updated settings file (cache / stat / opcache) which we have seen before but it was back.  This would leave the db location for themes etc as 127.0.0.1
Since I had to poke around, did some psr updates and some php cleanup
> Fixes and updates to install/upgrade scripts
